const profileStoreKey='beadDifferentProfiles';
const sessionStoreKey='beadDifferentAccount';
const profileEscape=(value)=>String(value??'').replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
const readProfiles=()=>{try{return JSON.parse(localStorage.getItem(profileStoreKey)||'[]');}catch(error){return [];}};
const saveProfiles=(profiles)=>localStorage.setItem(profileStoreKey,JSON.stringify(profiles));
const localAccount=()=>{try{return JSON.parse(localStorage.getItem(sessionStoreKey)||'null');}catch(error){return null;}};
const cloudClient=()=>window.beadSupabase||null;
const cloudUser=async()=>{const client=cloudClient();if(!client)return null;const {data}=await client.auth.getUser();return data?.user||null;};
async function profileCredential(value){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,'0')).join('');}
function localAddressFields(fields){return {id:fields.id||`address-${Date.now()}`,label:String(fields.label||'Address'),recipient_name:String(fields.recipient_name||''),address_line1:String(fields.address_line1||''),address_line2:String(fields.address_line2||''),city:String(fields.city||''),state:String(fields.state||''),postal_code:String(fields.postal_code||''),country:String(fields.country||'US'),is_default:Boolean(fields.is_default)};}
function setSession(account){const next={id:account.id,name:account.name||account.full_name||account.email,email:account.email,status:account.status||'active',role:account.role||'customer'};localStorage.setItem(sessionStoreKey,JSON.stringify(next));window.dispatchEvent(new Event('bead-account-changed'));return next;}
async function createCustomerProfile(fields){const name=String(fields.name||'').trim();const email=String(fields.email||'').trim().toLowerCase();if(cloudClient()){const {data,error}=await cloudClient().auth.signUp({email,password:fields.password,options:{data:{full_name:name}}});if(error)throw error;if(!data.user)throw new Error('Account could not be created.');if(!data.session)throw new Error('Account created. Check your email to confirm your account before signing in.');const user=data.user;await cloudClient().from('profiles').upsert({id:user.id,email:user.email,full_name:name,role:'customer',status:'active'},{onConflict:'id'});await saveAccountDetails({address:fields,marketingOptIn:fields.marketing_opt_in==='on'});return setSession({id:user.id,name,email:user.email,role:'customer',status:'active'});}const profiles=readProfiles();if(profiles.some((profile)=>profile.email===email))throw new Error('An account with that email already exists.');const profile={id:`member-${Date.now()}`,name,email,passwordHash:await profileCredential(fields.password),createdAt:new Date().toISOString(),status:'active',addresses:fields.address_line1?[localAddressFields(fields)]:[],marketingOptIn:fields.marketing_opt_in==='on',favorites:[],orders:[]};profiles.push(profile);saveProfiles(profiles);return setSession(profile);}
async function signInCustomer(email,password){const normalized=String(email||'').trim().toLowerCase();if(cloudClient()){const {data,error}=await cloudClient().auth.signInWithPassword({email:normalized,password});if(error)throw error;if(!data.user.email_confirmed_at)throw new Error('Please confirm your email before signing in.');const {data:profile}=await cloudClient().from('profiles').select('id,email,full_name,status,role').eq('id',data.user.id).maybeSingle();if(profile?.status==='blocked')throw new Error('This account is blocked.');return setSession({id:data.user.id,name:profile?.full_name||data.user.email,email:profile?.email||data.user.email,status:profile?.status||'active',role:profile?.role||'customer'});}const profile=readProfiles().find((entry)=>entry.email===normalized);if(!profile||profile.passwordHash!==await profileCredential(password))throw new Error('Email or password is incorrect.');if(profile.status==='blocked')throw new Error('This account is blocked.');return setSession(profile);}
async function requestPasswordReset(email){const normalized=String(email||'').trim().toLowerCase();if(!normalized)throw new Error('Enter your email address first.');if(cloudClient()){const {error}=await cloudClient().auth.resetPasswordForEmail(normalized,{redirectTo:`${window.location.origin}${window.location.pathname}?reset=1`});if(error)throw error;return true;}throw new Error('Password recovery is only available after connecting an account to the live store.');}
async function updateCustomerPassword(password){if(!cloudClient())throw new Error('Password recovery is only available after connecting an account to the live store.');if(String(password||'').length<8)throw new Error('Password must be at least 8 characters.');const {error}=await cloudClient().auth.updateUser({password});if(error)throw error;return true;}
async function signOutCustomer(){if(cloudClient())await cloudClient().auth.signOut();localStorage.removeItem(sessionStoreKey);window.dispatchEvent(new Event('bead-account-changed'));}
async function saveAccountDetails({name,address,marketingOptIn}){const account=localAccount();const user=await cloudUser();if(user){if(name!==undefined){const {error}=await cloudClient().from('profiles').update({full_name:String(name).trim(),updated_at:new Date().toISOString()}).eq('id',user.id);if(error)throw error;}if(marketingOptIn!==undefined){const {error}=await cloudClient().from('customer_preferences').upsert({user_id:user.id,marketing_opt_in:Boolean(marketingOptIn),updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;}if(address?.address_line1){if(address.is_default)await cloudClient().from('customer_addresses').update({is_default:false}).eq('user_id',user.id);const payload=localAddressFields(address);delete payload.id;if(address.id)payload.id=address.id;const {data,error}=await cloudClient().from('customer_addresses').upsert({...payload,user_id:user.id,updated_at:new Date().toISOString()},{onConflict:'id'}).select().single();if(error)throw error;return data;}return true;}const profiles=readProfiles();const profile=profiles.find((entry)=>entry.id===account?.id);if(!profile)return false;if(name!==undefined)profile.name=String(name).trim();if(marketingOptIn!==undefined)profile.marketingOptIn=Boolean(marketingOptIn);if(address?.address_line1){if(address.is_default)(profile.addresses||[]).forEach((entry)=>{entry.is_default=false;});profile.addresses=profile.addresses||[];const next=localAddressFields(address);const index=profile.addresses.findIndex((entry)=>entry.id===next.id);if(index<0)profile.addresses.push(next);else profile.addresses[index]=next;}saveProfiles(profiles);setSession(profile);return true;}
async function addresses(){const user=await cloudUser();if(user){const {data,error}=await cloudClient().from('customer_addresses').select('*').eq('user_id',user.id).order('is_default',{ascending:false}).order('updated_at',{ascending:false});if(error)throw error;return data||[];}return readProfiles().find((entry)=>entry.id===localAccount()?.id)?.addresses||[];}
async function deleteAddress(id){const user=await cloudUser();if(user){const {error}=await cloudClient().from('customer_addresses').delete().eq('id',id).eq('user_id',user.id);if(error)throw error;return;}const profiles=readProfiles();const profile=profiles.find((entry)=>entry.id===localAccount()?.id);if(profile)profile.addresses=(profile.addresses||[]).filter((entry)=>entry.id!==id);saveProfiles(profiles);}
async function preferences(){const user=await cloudUser();if(user){const {data}=await cloudClient().from('customer_preferences').select('marketing_opt_in').eq('user_id',user.id).maybeSingle();return Boolean(data?.marketing_opt_in);}return Boolean(readProfiles().find((entry)=>entry.id===localAccount()?.id)?.marketingOptIn);}
async function favorites(){const user=await cloudUser();if(user){const {data,error}=await cloudClient().from('customer_favorites').select('product_id,products(id,external_id,name,price)').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;return data||[];}return (readProfiles().find((entry)=>entry.id===localAccount()?.id)?.favorites||[]).map((id)=>({product_id:id}));}
async function orders(){const user=await cloudUser();if(user){const {data,error}=await cloudClient().from('orders').select('id,status,total,shipping_name,shipping_address,carrier,tracking_number,shipped_at,created_at,order_items(id,product_id,product_name,quantity,unit_price,selected_options,products(external_id))').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;return data||[];}return readProfiles().find((entry)=>entry.id===localAccount()?.id)?.orders||[];}
async function reviewableProductIds(){const records=await orders();return new Set(records.flatMap((order)=>order.order_items||[]).map((item)=>item.products?.external_id||item.product_id||item.productId).filter(Boolean));}
async function syncCloudSession(session){const user=session?.user;if(!user){localStorage.removeItem(sessionStoreKey);window.dispatchEvent(new Event('bead-account-changed'));return;}const {data:profile}=await cloudClient().from('profiles').select('id,email,full_name,status,role').eq('id',user.id).maybeSingle();setSession({id:user.id,name:profile?.full_name||user.user_metadata?.full_name||user.email,email:profile?.email||user.email,status:profile?.status||'active',role:profile?.role||'customer'});}
if(cloudClient())cloudClient().auth.onAuthStateChange((_event,session)=>{setTimeout(()=>syncCloudSession(session),0);});
window.customerAccounts={profiles:readProfiles,create:createCustomerProfile,signIn:signInCustomer,requestPasswordReset,updatePassword:updateCustomerPassword,signOut:signOutCustomer,current:localAccount,saveDetails:saveAccountDetails,addresses,deleteAddress,preferences,favorites,orders,reviewableProductIds};
