const profileStoreKey='beadDifferentProfiles';
const sessionStoreKey='beadDifferentAccount';
const profileEscape=(value)=>String(value??'').replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
const readProfiles=()=>{try{return JSON.parse(localStorage.getItem(profileStoreKey)||'[]');}catch(error){return [];}};
const saveProfiles=(profiles)=>localStorage.setItem(profileStoreKey,JSON.stringify(profiles));
async function profileCredential(value){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,'0')).join('');}
async function createCustomerProfile({name,email,password}){const normalized=email.trim().toLowerCase();const profiles=readProfiles();if(profiles.some((profile)=>profile.email===normalized))throw new Error('An account with that email already exists.');const profile={id:`member-${Date.now()}`,name:name.trim(),email:normalized,passwordHash:await profileCredential(password),createdAt:new Date().toISOString(),status:'active'};profiles.push(profile);saveProfiles(profiles);localStorage.setItem(sessionStoreKey,JSON.stringify({id:profile.id,name:profile.name,email:profile.email}));return profile;}
async function signInCustomer(email,password){if(window.beadSupabase){const {data,error}=await window.beadSupabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error)throw error;if(!data.user.email_confirmed_at){await window.beadSupabase.auth.signOut();throw new Error('Please confirm your email before signing in.');}const {data:profile}=await window.beadSupabase.from('profiles').select('id,email,full_name,status,role').eq('id',data.user.id).maybeSingle();const account={id:data.user.id,name:profile?.full_name||data.user.email,email:profile?.email||data.user.email,status:profile?.status||'active',role:profile?.role||'customer'};localStorage.setItem(sessionStoreKey,JSON.stringify(account));return account;}const normalized=email.trim().toLowerCase();const profile=readProfiles().find((entry)=>entry.email===normalized);if(!profile||profile.passwordHash!==await profileCredential(password))throw new Error('Email or password is incorrect.');if(profile.status==='blocked')throw new Error('This account is blocked.');localStorage.setItem(sessionStoreKey,JSON.stringify({id:profile.id,name:profile.name,email:profile.email}));return profile;}
async function createCustomerProfile({name,email,password}){if(window.beadSupabase){const {data,error}=await window.beadSupabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{data:{full_name:name.trim()}}});if(error)throw error;if(!data.session)throw new Error('Account created. Check your email to confirm your account, then sign in.');if(!data.user.email_confirmed_at){await window.beadSupabase.auth.signOut();throw new Error('Account created. Check your email to confirm your account before signing in.');}const account={id:data.user.id,name:name.trim(),email:data.user.email,role:'customer',status:'active'};localStorage.setItem(sessionStoreKey,JSON.stringify(account));return account;}const normalized=email.trim().toLowerCase();const profiles=readProfiles();if(profiles.some((profile)=>profile.email===normalized))throw new Error('An account with that email already exists.');const profile={id:`member-${Date.now()}`,name:name.trim(),email:normalized,passwordHash:await profileCredential(password),createdAt:new Date().toISOString(),status:'active'};profiles.push(profile);saveProfiles(profiles);localStorage.setItem(sessionStoreKey,JSON.stringify({id:profile.id,name:profile.name,email:profile.email}));return profile;}
async function signOutCustomer(){if(window.beadSupabase)await window.beadSupabase.auth.signOut();localStorage.removeItem(sessionStoreKey);}
function currentCustomer(){try{return JSON.parse(localStorage.getItem(sessionStoreKey)||'null');}catch(error){return null;}}
if(window.beadSupabase){window.beadSupabase.auth.onAuthStateChange((_event,session)=>{if(session?.user){localStorage.setItem(sessionStoreKey,JSON.stringify({id:session.user.id,name:session.user.user_metadata?.full_name||session.user.email,email:session.user.email}));}else localStorage.removeItem(sessionStoreKey);window.dispatchEvent(new Event('bead-account-changed'));});}
window.customerAccounts={profiles:readProfiles,create:createCustomerProfile,signIn:signInCustomer,signOut:signOutCustomer,current:currentCustomer};
