const profileStoreKey='beadDifferentProfiles';
const sessionStoreKey='beadDifferentAccount';
const profileEscape=(value)=>String(value??'').replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
const readProfiles=()=>{try{return JSON.parse(localStorage.getItem(profileStoreKey)||'[]');}catch(error){return [];}};
const saveProfiles=(profiles)=>localStorage.setItem(profileStoreKey,JSON.stringify(profiles));
const localAccount=()=>{try{return JSON.parse(localStorage.getItem(sessionStoreKey)||'null');}catch(error){return null;}};
const cloudClient=()=>window.beadSupabase||null;
const cloudReadyClient=async()=>{try{return window.beadSupabase||await window.beadSupabaseReady||null;}catch(error){return null;}};
const adminAuthRequired=()=>new URLSearchParams(window.location.search).get('return')==='admin.html';
const cloudUser=async()=>{const client=await cloudReadyClient();if(!client)return null;const {data}=await client.auth.getUser();return data?.user||null;};
async function profileCredential(value){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,'0')).join('');}
function localAddressFields(fields){return {id:fields.id||`address-${Date.now()}`,label:String(fields.label||'Address'),recipient_name:String(fields.recipient_name||''),address_line1:String(fields.address_line1||''),address_line2:String(fields.address_line2||''),city:String(fields.city||''),state:String(fields.state||''),postal_code:String(fields.postal_code||''),country:String(fields.country||'US'),is_default:Boolean(fields.is_default)};}
function setSession(account){const next={id:account.id,name:account.name||account.full_name||account.email,email:account.email,status:account.status||'active',role:account.role||'customer'};localStorage.setItem(sessionStoreKey,JSON.stringify(next));window.dispatchEvent(new Event('bead-account-changed'));return next;}
async function createCustomerProfile(fields){const name=String(fields.name||'').trim();const email=String(fields.email||'').trim().toLowerCase();const client=await cloudReadyClient();if(!client&&adminAuthRequired())throw new Error('The connected store database is unavailable. Refresh the store preview and try again.');if(client){const {data,error}=await client.auth.signUp({email,password:fields.password,options:{data:{full_name:name}}});if(error)throw error;if(!data.user)throw new Error('Account could not be created.');if(!data.session)throw new Error('Account created. Check your email to confirm your account before signing in.');const user=data.user;await client.from('profiles').upsert({id:user.id,email:user.email,full_name:name,role:'customer',status:'active'},{onConflict:'id'});await saveAccountDetails({address:fields,marketingOptIn:fields.marketing_opt_in==='on'});return setSession({id:user.id,name,email:user.email,role:'customer',status:'active'});}const profiles=readProfiles();if(profiles.some((profile)=>profile.email===email))throw new Error('An account with that email already exists.');const profile={id:`member-${Date.now()}`,name,email,passwordHash:await profileCredential(fields.password),createdAt:new Date().toISOString(),status:'active',addresses:fields.address_line1?[localAddressFields(fields)]:[],marketingOptIn:fields.marketing_opt_in==='on',favorites:[],orders:[]};profiles.push(profile);saveProfiles(profiles);return setSession(profile);}
async function signInCustomer(email,password){const normalized=String(email||'').trim().toLowerCase();const client=await cloudReadyClient();if(!client&&adminAuthRequired())throw new Error('The connected store database is unavailable. Refresh the store preview and try again.');if(client){const {data,error}=await client.auth.signInWithPassword({email:normalized,password});if(error)throw error;if(!data.user.email_confirmed_at)throw new Error('Please confirm your email before signing in.');const {data:profile}=await client.from('profiles').select('id,email,full_name,status,role').eq('id',data.user.id).maybeSingle();if(profile?.status==='blocked')throw new Error('This account is blocked.');return setSession({id:data.user.id,name:profile?.full_name||data.user.email,email:profile?.email||data.user.email,status:profile?.status||'active',role:profile?.role||'customer'});}const profile=readProfiles().find((entry)=>entry.email===normalized);if(!profile||profile.passwordHash!==await profileCredential(password))throw new Error('Email or password is incorrect.');if(profile.status==='blocked')throw new Error('This account is blocked.');return setSession(profile);}
async function requestPasswordReset(email){const normalized=String(email||'').trim().toLowerCase();if(!normalized)throw new Error('Enter your email address first.');const client=await cloudReadyClient();if(client){const {error}=await client.auth.resetPasswordForEmail(normalized,{redirectTo:`${window.location.origin}${window.location.pathname}?reset=1`});if(error)throw error;return true;}throw new Error('Password recovery is only available after connecting an account to the live store.');}
async function updateCustomerPassword(password){const client=await cloudReadyClient();if(!client)throw new Error('Password recovery is only available after connecting an account to the live store.');if(String(password||'').length<8)throw new Error('Password must be at least 8 characters.');const {error}=await client.auth.updateUser({password});if(error)throw error;return true;}
async function signOutCustomer(){const client=await cloudReadyClient();if(client)await client.auth.signOut();localStorage.removeItem(sessionStoreKey);window.customerStore?.clearForSignOut?.();window.dispatchEvent(new Event('bead-account-changed'));}
async function saveAccountDetails({name,address,marketingOptIn}){const account=localAccount();const user=await cloudUser();if(user){if(name!==undefined){const {error}=await cloudClient().from('profiles').update({full_name:String(name).trim(),updated_at:new Date().toISOString()}).eq('id',user.id);if(error)throw error;}if(marketingOptIn!==undefined){const {error}=await cloudClient().from('customer_preferences').upsert({user_id:user.id,marketing_opt_in:Boolean(marketingOptIn),updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;}if(address?.address_line1){if(address.is_default){const reset=await cloudClient().from('customer_addresses').update({is_default:false}).eq('user_id',user.id);if(reset.error)throw reset.error;}const payload=localAddressFields(address);delete payload.id;if(address.id)payload.id=address.id;const {data,error}=await cloudClient().from('customer_addresses').upsert({...payload,user_id:user.id,updated_at:new Date().toISOString()},{onConflict:'id'}).select().single();if(error)throw error;return data;}return true;}const profiles=readProfiles();const profile=profiles.find((entry)=>entry.id===account?.id);if(!profile)return false;if(name!==undefined)profile.name=String(name).trim();if(marketingOptIn!==undefined)profile.marketingOptIn=Boolean(marketingOptIn);if(address?.address_line1){if(address.is_default)(profile.addresses||[]).forEach((entry)=>{entry.is_default=false;});profile.addresses=profile.addresses||[];const next=localAddressFields(address);const index=profile.addresses.findIndex((entry)=>entry.id===next.id);if(index<0)profile.addresses.push(next);else profile.addresses[index]=next;}saveProfiles(profiles);setSession(profile);return true;}
async function addresses(){const user=await cloudUser();if(user){const {data,error}=await cloudClient().from('customer_addresses').select('*').eq('user_id',user.id).order('is_default',{ascending:false}).order('updated_at',{ascending:false});if(error)throw error;return data||[];}return readProfiles().find((entry)=>entry.id===localAccount()?.id)?.addresses||[];}
async function deleteAddress(id){const user=await cloudUser();if(user){const {error}=await cloudClient().from('customer_addresses').delete().eq('id',id).eq('user_id',user.id);if(error)throw error;return;}const profiles=readProfiles();const profile=profiles.find((entry)=>entry.id===localAccount()?.id);if(profile)profile.addresses=(profile.addresses||[]).filter((entry)=>entry.id!==id);saveProfiles(profiles);}
async function preferences(){const user=await cloudUser();if(user){const {data}=await cloudClient().from('customer_preferences').select('marketing_opt_in').eq('user_id',user.id).maybeSingle();return Boolean(data?.marketing_opt_in);}return Boolean(readProfiles().find((entry)=>entry.id===localAccount()?.id)?.marketingOptIn);}
async function reviews(){const user=await cloudUser();if(user){const {data,error}=await cloudClient().from('reviews').select('id,review_type,rating,body,photos,status,verified_purchase,created_at,products(name,external_id)').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;return data||[];}const account=localAccount();let entries=[];try{entries=JSON.parse(localStorage.getItem('beadDifferentReviews')||'[]');}catch(error){}return entries.filter((entry)=>entry.email===account?.email).sort((first,second)=>Date.parse(second.createdAt||0)-Date.parse(first.createdAt||0));}
const favoritePresentation=(product,catalog)=>{const match=catalog.find((entry)=>[entry.id,entry.externalId,entry.databaseId].filter(Boolean).some((value)=>String(value)===String(product.id||product.external_id||'')));const variants=(match?.options||[]).flatMap((option)=>option.values||[]).filter((value)=>typeof value==='object'&&Number.isFinite(Number(value.price)));const lowest=variants.reduce((current,value)=>Number(value.price)<Number(current.price)?value:current,variants[0]);return{image:match?.image||product.image,price:lowest?.price??match?.displayPrice??product.price,unit_type:lowest?.unitType||match?.unitType||product.unit_type||'Each'};};async function favorites(){const user=await cloudUser();if(window.catalogReady)await window.catalogReady;const catalog=window.storeCatalog?.()||[];if(user){const {data,error}=await cloudClient().from('customer_favorites').select('product_id,products(id,external_id,name,price,product_images(url,sort_order,media_type))').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;return(data||[]).map((entry)=>{const product=entry.products||{};return{...entry,products:{...product,...favoritePresentation(product,catalog)}};});}return(readProfiles().find((entry)=>entry.id===localAccount()?.id)?.favorites||[]).map((id)=>{const product=catalog.find((entry)=>[entry.id,entry.externalId,entry.databaseId].filter(Boolean).some((value)=>String(value)===String(id)));return{product_id:id,products:{name:product?.name,external_id:product?.externalId||id,...favoritePresentation(product||{},catalog)}};});}
async function orders(){const user=await cloudUser();if(user){const {data,error}=await cloudClient().from('orders').select('id,status,total,shipping_name,shipping_address,carrier,tracking_number,shipped_at,created_at,order_items(id,product_id,product_name,quantity,unit_price,selected_options,products(external_id))').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;return data||[];}return readProfiles().find((entry)=>entry.id===localAccount()?.id)?.orders||[];}
async function reviewableProductIds(){const records=await orders();const eligible=new Set(['paid','processing','shipped','completed']);return new Set(records.filter((order)=>eligible.has(order.status)).flatMap((order)=>order.order_items||[]).map((item)=>item.products?.external_id||item.product_id||item.productId).filter(Boolean));}
async function syncCloudSession(session){const user=session?.user;if(!user){localStorage.removeItem(sessionStoreKey);window.dispatchEvent(new Event('bead-account-changed'));return;}const {data:profile}=await cloudClient().from('profiles').select('id,email,full_name,status,role').eq('id',user.id).maybeSingle();setSession({id:user.id,name:profile?.full_name||user.user_metadata?.full_name||user.email,email:profile?.email||user.email,status:profile?.status||'active',role:profile?.role||'customer'});}
if(window.beadSupabaseReady)window.beadSupabaseReady.then((client)=>client?.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>syncCloudSession(session),0);})).catch(()=>{});
async function waitlist(){const user=await cloudUser();if(user){const {data,error}=await cloudClient().from('waitlist_entries').select('id,status,requested_quantity,requested_total_quantity,selected_options,created_at,products(name,external_id),inventory_skus(sku,name)').eq('user_id',user.id).eq('status','waiting').order('created_at',{ascending:false});if(error)throw error;return data||[];}const account=localAccount();let entries=[];try{entries=JSON.parse(localStorage.getItem('beadDifferentRestockWaitlist')||'[]');}catch(error){}return entries.filter((entry)=>entry.accountEmail===account?.email&&entry.status==='waiting').map((entry)=>({...entry,products:{name:entry.productName,external_id:entry.productId},inventory_skus:{sku:entry.inventorySku,name:entry.inventorySku}}));}
async function removeWaitlist(entry){const user=await cloudUser();if(user&&entry?.id){const {error}=await cloudClient().from('waitlist_entries').delete().eq('id',entry.id).eq('user_id',user.id);if(error)throw error;return true;}const account=localAccount();let entries=[];try{entries=JSON.parse(localStorage.getItem('beadDifferentRestockWaitlist')||'[]');}catch(error){}const next=entries.filter((saved)=>!(saved.accountEmail===account?.email&&saved.productId===entry?.products?.external_id&&saved.inventorySku===(entry?.inventory_skus?.sku||'')));localStorage.setItem('beadDifferentRestockWaitlist',JSON.stringify(next));return next.length!==entries.length;}
const rewardStoreKey='beadDifferentRewardCodes';
const rewardSettings=()=>{const config=window.productStoreConfig||{};return{threshold:Math.max(0.01,Number(config.rewardThreshold)||35),discountPercent:Math.min(100,Math.max(0.01,Number(config.rewardDiscountPercent)||5))};};
const qualifyingOrderSpend=(orders)=>orders.filter((order)=>['paid','processing','shipped','completed'].includes(String(order.status||'').toLowerCase())).reduce((total,order)=>{const subtotal=Number(order.subtotal);if(Number.isFinite(subtotal))return total+Math.max(0,subtotal);return total+(order.order_items||[]).reduce((lineTotal,item)=>lineTotal+Math.max(0,Number(item.unit_price)||0)*Math.max(0,Number(item.quantity)||0),0);},0);
const readRewardCodes=()=>{try{return JSON.parse(localStorage.getItem(rewardStoreKey)||'[]');}catch(error){return [];}};
const saveRewardCodes=(records)=>localStorage.setItem(rewardStoreKey,JSON.stringify(records));
async function rewardStatus(){const user=await cloudUser();if(user){const {data,error}=await cloudClient().rpc('get_my_reward_status');if(!error)return data||{};const settings=rewardSettings();return{spend:0,threshold:settings.threshold,discountPercent:settings.discountPercent,progress:0,available:false,code:null,rewardNumber:0};}const account=localAccount();if(!account)throw new Error('Please sign in to view your rewards.');const settings=rewardSettings();const ordersList=await orders();const spend=qualifyingOrderSpend(ordersList);const rewardNumber=Math.floor(spend/settings.threshold);const records=readRewardCodes();const current=records.find((entry)=>entry.accountId===account.id&&entry.rewardNumber===rewardNumber);const cycleSpend=rewardNumber?spend-(rewardNumber-1)*settings.threshold:spend;return{spend,threshold:settings.threshold,discountPercent:settings.discountPercent,progress:current?.redeemedAt?Math.max(0,spend-(rewardNumber*settings.threshold)):Math.min(settings.threshold,Math.max(0,cycleSpend)),available:rewardNumber>0&&(!current||!current.redeemedAt),code:current?.redeemedAt?null:current?.code||null,rewardNumber};}
async function claimReward(){const user=await cloudUser();if(user){const {data,error}=await cloudClient().rpc('claim_my_reward');if(error)throw error;return data||{};}const account=localAccount();if(!account)throw new Error('Please sign in to claim your reward.');const status=await rewardStatus();if(!status.available)throw new Error('This reward is not available yet.');const records=readRewardCodes();const existing=records.find((entry)=>entry.accountId===account.id&&entry.rewardNumber===status.rewardNumber&&!entry.redeemedAt);if(existing)return{code:existing.code,threshold:existing.threshold,discountPercent:existing.discountPercent,rewardNumber:existing.rewardNumber};const randomBytes=new Uint8Array(6);crypto.getRandomValues(randomBytes);const code='BD-REWARD-'+[...randomBytes].map((byte)=>byte.toString(16).padStart(2,'0')).join('').toUpperCase();const record={accountId:account.id,email:account.email,rewardNumber:status.rewardNumber,threshold:status.threshold,discountPercent:status.discountPercent,code,redeemedAt:null,createdAt:new Date().toISOString()};records.push(record);saveRewardCodes(records);return record;}
async function loadAccountView(view='overview',page=1){
  const currentPage=Math.max(1,Number(page)||1);
  const pageSize=25;
  const user=await cloudUser();
  if(!user){
    const account=localAccount();
    const profile=readProfiles().find((entry)=>entry.id===account?.id)||{};
    const localFavorites=(profile.favorites||[]).map((id)=>{const product=(window.storeCatalog?.()||[]).find((entry)=>[entry.id,entry.externalId,entry.databaseId].filter(Boolean).some((value)=>String(value)===String(id)));return{product_id:id,products:{name:product?.name,external_id:product?.externalId||id,...favoritePresentation(product||{},window.storeCatalog?.()||[])}};});
    const localOrders=profile.orders||[];
    const localReviews=await reviews();
    const localWaitlist=await waitlist();
    const catalog=window.storeCatalog?.()||[];
    const localWaitlistRows=localWaitlist.map((entry)=>{const product=entry.products||{};return{...entry,products:{...product,...favoritePresentation(product,catalog)}};});
    return{addresses:profile.addresses||[],marketingOptIn:Boolean(profile.marketingOptIn),favorites:view==='favorites'?localFavorites.slice((currentPage-1)*pageSize,currentPage*pageSize):localFavorites.slice(0,2),favoriteCount:localFavorites.length,orders:view==='orders'?localOrders.slice((currentPage-1)*pageSize,currentPage*pageSize):localOrders.slice(0,2),orderCount:localOrders.length,reviews:view==='reviews'?localReviews.slice((currentPage-1)*pageSize,currentPage*pageSize):localReviews.slice(0,2),reviewCount:localReviews.length,waitlist:view==='waitlist'?localWaitlistRows.slice((currentPage-1)*pageSize,currentPage*pageSize):localWaitlist.slice(0,2),waitlistCount:localWaitlist.length,rewardStatus:view==='overview'?await rewardStatus():null};
  }
  const offset=(currentPage-1)*pageSize;
  const [addressResult,preferenceResult,favoriteResult,favoriteCountResult,orderResult,orderCountResult,reviewResult,reviewCountResult,waitlistResult,waitlistCountResult,rewardResult]=await Promise.all([
    cloudClient().from('customer_addresses').select('*').eq('user_id',user.id).order('is_default',{ascending:false}).order('updated_at',{ascending:false}),
    cloudClient().from('customer_preferences').select('marketing_opt_in').eq('user_id',user.id).maybeSingle(),
    cloudClient().from('customer_favorites').select('product_id,products(id,external_id,name,price,product_images(url,sort_order,media_type))').eq('user_id',user.id).order('created_at',{ascending:false}).range(view==='favorites'?offset:0,view==='favorites'?offset+pageSize-1:1),
    cloudClient().from('customer_favorites').select('product_id',{count:'exact',head:true}).eq('user_id',user.id),
    cloudClient().from('orders').select('id,status,total,shipping_name,shipping_address,carrier,tracking_number,shipped_at,created_at,order_items(id,product_id,product_name,quantity,unit_price,selected_options,products(external_id))').eq('user_id',user.id).order('created_at',{ascending:false}).range(view==='orders'?offset:0,view==='orders'?offset+pageSize-1:1),
    cloudClient().from('orders').select('id',{count:'exact',head:true}).eq('user_id',user.id),
    cloudClient().from('reviews').select('id,review_type,rating,body,photos,status,verified_purchase,created_at,products(name,external_id)').eq('user_id',user.id).order('created_at',{ascending:false}).range(view==='reviews'?offset:0,view==='reviews'?offset+pageSize-1:1),
    cloudClient().from('reviews').select('id',{count:'exact',head:true}).eq('user_id',user.id),
    cloudClient().from('waitlist_entries').select('id,status,requested_quantity,requested_total_quantity,selected_options,created_at,products(name,external_id,product_images(url,sort_order,media_type)),inventory_skus(sku,name)').eq('user_id',user.id).eq('status','waiting').order('created_at',{ascending:false}).range(view==='waitlist'?offset:0,view==='waitlist'?offset+pageSize-1:1),
    cloudClient().from('waitlist_entries').select('id',{count:'exact',head:true}).eq('user_id',user.id).eq('status','waiting'),
    view==='overview'?cloudClient().rpc('get_my_reward_status'):Promise.resolve({data:null,error:null})
  ]);
  for(const result of [addressResult,preferenceResult,favoriteResult,favoriteCountResult,orderResult,orderCountResult,reviewResult,reviewCountResult,waitlistResult,waitlistCountResult,rewardResult])if(result.error)throw result.error;
  if(window.catalogReady)await window.catalogReady;  const catalog=window.storeCatalog?.()||[];
  const favoriteRows=(favoriteResult.data||[]).map((entry)=>{const product=entry.products||{};return{...entry,products:{...product,...favoritePresentation(product,catalog)}};});
  const waitlistRows=(waitlistResult.data||[]).map((entry)=>{const product=entry.products||{};return{...entry,products:{...product,...favoritePresentation(product,catalog)}};});
  return{addresses:addressResult.data||[],marketingOptIn:Boolean(preferenceResult.data?.marketing_opt_in),favorites:favoriteRows,favoriteCount:favoriteCountResult.count||0,orders:orderResult.data||[],orderCount:orderCountResult.count||0,reviews:reviewResult.data||[],reviewCount:reviewCountResult.count||0,waitlist:waitlistRows,waitlistCount:waitlistCountResult.count||0,rewardStatus:rewardResult.data||null};
}
const signInForCurrentRoute=signInCustomer;
signInCustomer=async(...args)=>{const account=await signInForCurrentRoute(...args);if(adminAuthRequired()){if(account?.role!=='admin'||account?.status!=='active'){localStorage.removeItem(sessionStoreKey);throw new Error('This account does not have active administrator access.');}window.location.replace('admin.html');}return account;};
window.customerAccounts={profiles:readProfiles,create:createCustomerProfile,signIn:signInCustomer,requestPasswordReset,updatePassword:updateCustomerPassword,signOut:signOutCustomer,current:localAccount,saveDetails:saveAccountDetails,addresses,deleteAddress,preferences,favorites,orders,reviews,waitlist,removeWaitlist,rewardStatus,claimReward,reviewableProductIds,loadView:loadAccountView};
