window.sanitizeRichText=(value)=>{const template=document.createElement('template');template.innerHTML=String(value??'');const allowed=new Set(['B','STRONG','I','EM','U','S','P','BR','H2','H3','BLOCKQUOTE','UL','OL','LI','DIV','FONT','SPAN']);template.content.querySelectorAll('*').forEach((element)=>{if(!allowed.has(element.tagName)){element.replaceWith(...element.childNodes);return;}[...element.attributes].forEach((attribute)=>{const name=attribute.name.toLowerCase();if(name==='style'){const safe=attribute.value.split(';').filter((rule)=>/^(font-family|font-size|font-weight|line-height|letter-spacing|text-align|margin|margin-top|margin-bottom)\s*:/i.test(rule.trim())).join(';');if(safe)element.setAttribute('style',safe);else element.removeAttribute('style');}else if(!['face','size'].includes(name))element.removeAttribute(attribute.name);});});return template.innerHTML;};
const formatFreeShippingMessage=(value)=>{const amount=Number(value);if(!Number.isFinite(amount)||amount<=0)return'FREE SHIPPING ON ALL ORDERS';const formatted=amount.toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:2});return`FREE SHIPPING ON ORDERS $${formatted}+`;};
window.updateAnnouncementBar=({freeShippingThreshold=35,smallBusiness='SMALL BUSINESS',bigCreativity='BIG CREATIVITY'}={})=>{const items=document.querySelectorAll('.announcement .announcement-item');if(items[0])items[0].textContent=formatFreeShippingMessage(freeShippingThreshold);if(items[1])items[1].textContent=String(smallBusiness||'SMALL BUSINESS');if(items[2])items[2].textContent=String(bigCreativity||'BIG CREATIVITY');};
window.updateFreeShippingAnnouncement=(value)=>window.updateAnnouncementBar({freeShippingThreshold:value});
window.siteThemeDefaults={buttonColor:'#050505',buttonTextColor:'#ffffff',bannerColor:'#e482a4',headerTextColor:'#111111',cartBadgeColor:'#e482a4',pageBackgroundColor:'#fffdfb',accentBackgroundColor:'#fff1f5',footerBackgroundColor:'#111111',footerHeaderTextColor:'#f185aa',footerButtonColor:'#f185aa',footerTextColor:'#ffffff'};
const safeThemeColor=(value,fallback)=>/^#[0-9a-f]{6}$/i.test(String(value||''))?String(value):fallback;
const safeThemeImageUrl=(value)=>{const url=String(value||'').trim();if(!url)return'';try{const parsed=new URL(url,window.location.href);if(!['http:','https:'].includes(parsed.protocol))return'';return parsed.href.replace(/["\\)]/g,'');}catch(error){return'';}};
window.applyStoreCategoryPhotos=(categoryPhotos={})=>{document.querySelectorAll('.category-grid a[data-filter]').forEach((card)=>{const image=card.querySelector('img');if(!image)return;const defaultUrl=image.dataset.themeDefaultSrc||(image.dataset.themeDefaultSrc=image.src);const safeUrl=safeThemeImageUrl(categoryPhotos[card.dataset.filter]);image.src=safeUrl||defaultUrl;});};
window.applyStoreTheme=(theme={},heroUrl='',categoryPhotos={},logoUrl='',storyUrl='',pageBackgroundImageUrl='',footerLogoUrl='')=>{const defaults=window.siteThemeDefaults||{};const values=Object.fromEntries(Object.entries(defaults).map(([key,fallback])=>[key,safeThemeColor(theme[key],fallback)]));const root=document.documentElement;Object.entries(values).forEach(([key,value])=>root.style.setProperty('--site-'+key.replace(/[A-Z]/g,(character)=>'-'+character.toLowerCase()),value));const safeBackgroundUrl=safeThemeImageUrl(pageBackgroundImageUrl);root.style.setProperty('--site-page-background-image',safeBackgroundUrl?`url("${safeBackgroundUrl}")`:'none');document.body?.setAttribute('data-theme-ready','true');const hero=document.querySelector('.hero');const safeUrl=safeThemeImageUrl(heroUrl);if(hero)hero.style.backgroundImage=safeUrl?`url("${safeUrl}")`:'';const logo=document.querySelector('.brand img');const safeLogoUrl=safeThemeImageUrl(logoUrl);if(logo)logo.src=safeLogoUrl||'logo-authoritative-transparent.png?v=2';const storyBar=document.querySelector('.story-bar');const storyMedia=storyBar?.querySelector('.story-bar-media');const story=storyMedia?.querySelector('img');const storyCopy=storyBar?.querySelector('.story-bar-copy');const safeStoryUrl=safeThemeImageUrl(storyUrl);if(storyBar){storyBar.removeAttribute('data-story-custom');if(storyMedia)storyMedia.style.backgroundImage="";if(story)story.src=safeStoryUrl||'story-test1-with-slogan.png';if(storyCopy)storyCopy.hidden=true;}window.applyStoreCategoryPhotos(categoryPhotos);};
const headerRoot=document.querySelector('#site-header');
if(headerRoot){headerRoot.innerHTML=`<div class="announcement"><span class="announcement-item">FREE SHIPPING ON ORDERS $35+</span><span class="announcement-divider">✦</span><span class="announcement-item">SMALL BUSINESS</span><span class="announcement-heart">♥</span><span class="announcement-item">BIG CREATIVITY</span></div><header class="header"><a class="brand" href="index.html"><img src="logo-authoritative-transparent.png?v=2" alt="Bead Different Co."></a><nav class="primary" aria-label="Main navigation"><a href="shop-all.html">Shop All</a><a href="our-story.html">Our Story</a><a href="contact.html">Contact</a></nav><div class="header-tools"><form class="search" action="search.html" method="get"><span class="search-icon" aria-hidden="true">⌕</span><input name="q" type="search" placeholder="Search beads, charms..." aria-label="Search beads, charms"></form><a class="tool" href="wishlist.html" aria-label="Wishlist">♡</a><a class="tool bag" href="shopping-bag.html" aria-label="Shopping bag"><span class="bag-icon"></span><i>0</i></a></div></header><nav class="store-nav" aria-label="Store categories"></nav>`;document.body.classList.add('shared-header-page');}
const headerLogo=document.querySelector('#site-header .brand img');
if(headerLogo){headerLogo.src='logo-authoritative-transparent.png?v=2';}
const footerRoot=document.querySelector('#site-footer')||document.body.appendChild(document.createElement('div'));footerRoot.id='site-footer';
if(footerRoot){footerRoot.innerHTML=`<section class="trust"><img class="trust-strip-image" src="trust-strip.png" alt="Fast shipping, small business, quality supplies, and amazing community"></section><footer class="footer" id="contact"><div class="footer-brand">Bead Different Co.<small>BEADS · SUPPLIES · CREATIVE POSSIBILITIES</small></div><div><b>Quick Links</b><a href="shop-all.html">Shop All</a><a href="our-story.html">About Us</a><a href="faq.html">FAQ</a><a href="shipping-returns.html">Shipping & Returns</a><a href="contact.html">Contact Us</a></div><div><b>Let’s Stay Connected</b><div class="social-links"><a href="#" aria-label="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="11" fill="currentColor"></circle><path fill="#111" d="M13.6 7.1h2V4.3c-.35-.05-1.55-.15-2.95-.15-2.92 0-4.92 1.78-4.92 5.05v2.82H4.5v3.13h3.23v7.86h3.95v-7.86h3.1l.49-3.13h-3.59V9.53c0-.91.25-1.53 1.92-1.53Z"></path></svg></a><a href="#" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="2"></rect><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"></circle><circle cx="17.5" cy="6.5" r="1.2" fill="currentColor"></circle></svg></a><a href="#" aria-label="TikTok"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M14.2 3h3.1c.25 1.65 1.18 2.74 2.7 3.28v3.08c-1.12-.03-2.13-.32-3.03-.86v6.13c0 3.76-2.25 5.98-5.64 5.98-3.02 0-5.23-1.97-5.23-4.76 0-3.02 2.45-5.08 5.91-4.69v3.2c-1.19-.22-2.15.27-2.15 1.35 0 .83.64 1.4 1.55 1.4 1.03 0 1.69-.68 1.69-2.37V3Z"></path></svg></a><a href="#" aria-label="Pinterest"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="10.5" fill="none" stroke="currentColor" stroke-width="2"></circle><path fill="currentColor" d="M10.1 19.4c.7-1.02 1.08-2.05 1.4-3.2.3.18.78.31 1.31.31 2.62 0 4.5-2.39 4.5-5.56 0-2.4-2.03-4.59-5.1-4.59-3.83 0-5.77 2.75-5.77 5.04 0 1.39.53 2.63 1.67 3.1.19.08.36 0 .42-.21l.16-.65c.05-.21.03-.28-.12-.47-.33-.4-.54-.92-.54-1.65 0-2.12 1.59-4.02 4.13-4.02 2.25 0 3.49 1.37 3.49 3.2 0 2.41-1.07 4.45-2.66 4.45-.88 0-1.54-.73-1.33-1.63.25-1.08.74-2.25.74-3.03 0-.7-.38-1.28-1.17-1.28-.93 0-1.67.96-1.67 2.25 0 .82.28 1.37.28 1.37s-.96 4.08-1.13 4.8c-.16.66-.18 1.4-.11 1.99Z"></path></svg></a><a href="#" aria-label="YouTube"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="2" y="5" width="20" height="14" rx="4" fill="currentColor"></rect><path fill="#111" d="m10 9 6 3-6 3V9Z"></path></svg></a></div></div><div><b>Join Our Newsletter</b><span>Get the latest drops, restocks and exclusive offers.</span><label><input placeholder="Enter your email"><button>SUBSCRIBE</button></label></div></footer>`;}
const footerBrand=footerRoot.querySelector('.footer-brand');
if(footerBrand){footerBrand.innerHTML='<img class="footer-logo" src="footer-logo.png" alt="Bead Different Co.">';}
const footerLogo=document.querySelector('#site-footer .footer-logo');
if(footerLogo){footerLogo.src='logo-user-transparent.png?v=1';}
window.storeCategories=[];
window.addEventListener('bead-categories-ready',()=>{const selected=new URLSearchParams(location.search).get('category')||'';document.querySelectorAll('.store-nav-select').forEach((select)=>{select.value=selected;});});
window.storeCategoryNameFor=(slug)=>{const value=String(slug||'').trim();return (window.storeCategories||[]).find(([categorySlug])=>categorySlug===value)?.[1]||'';};
document.querySelectorAll('.store-nav').forEach((nav)=>{if(nav.parentElement.classList.contains('store-nav-shell'))return;const shell=document.createElement('div');shell.className='store-nav-shell';const previous=document.createElement('button');previous.className='store-nav-arrow';previous.type='button';previous.setAttribute('aria-label','Previous categories');previous.textContent='‹';const next=document.createElement('button');next.className='store-nav-arrow';next.type='button';next.setAttribute('aria-label','Next categories');next.textContent='›';nav.parentNode.insertBefore(shell,nav);shell.append(previous,nav,next);previous.addEventListener('click',()=>nav.scrollBy({left:-nav.clientWidth*.8,behavior:'smooth'}));next.addEventListener('click',()=>nav.scrollBy({left:nav.clientWidth*.8,behavior:'smooth'}));});
document.querySelectorAll('.store-nav-shell').forEach((shell)=>{const select=document.createElement('select');select.className='store-nav-select';select.setAttribute('aria-label','Browse categories');select.innerHTML='<option value="">Browse categories</option>';select.addEventListener('change',()=>{if(select.value)window.location.href=`category.html?category=${select.value}`;});shell.append(select);});
const categoryLayout=document.body.dataset.categoryLayout==='true';
if(categoryLayout){document.body.classList.add('category-layout');document.querySelectorAll('.store-nav').forEach((nav)=>{nav.classList.add('category-sidebar');const shell=nav.closest('.store-nav-shell');const previous=shell?.querySelector('.store-nav-arrow');const next=shell?.querySelector('.store-nav-arrow:last-child');if(previous&&next){previous.textContent='↑';next.textContent='↓';previous.setAttribute('aria-label','Scroll categories up');next.setAttribute('aria-label','Scroll categories down');previous.addEventListener('click',()=>nav.scrollBy({top:-nav.clientHeight*.8,behavior:'smooth'}));next.addEventListener('click',()=>nav.scrollBy({top:nav.clientHeight*.8,behavior:'smooth'}));}});document.querySelector('#site-footer')?.classList.add('category-footer');}
document.querySelectorAll('.store-nav').forEach((nav)=>{const first=nav.querySelector('a');if(!first)return;first.href='shop-all.html';const label=first.querySelector('span');if(label)label.textContent='Shop All';else first.textContent='Shop All';});
if(categoryLayout&&window.matchMedia('(max-width:700px)').matches){document.querySelectorAll('.store-nav-shell').forEach((shell)=>{const arrows=shell.querySelectorAll('.store-nav-arrow');if(arrows.length===2){arrows[0].textContent='‹';arrows[1].textContent='›';arrows[0].setAttribute('aria-label','Scroll categories left');arrows[1].setAttribute('aria-label','Scroll categories right');}});}
document.querySelectorAll('.footer').forEach((footer)=>{const links=footer.querySelector('.footer-links')||footer.querySelector('div:nth-child(2)');if(links&&!links.querySelector('[href="reviews.html"]')){const reviewLink=document.createElement('a');reviewLink.href='reviews.html';reviewLink.textContent='Leave a Review';links.append(reviewLink);}});
document.querySelectorAll('.header-tools').forEach((tools)=>{if(!tools.querySelector('[href="account.html"]')){const accountLink=document.createElement('a');accountLink.href='account.html';accountLink.className='tool account-link';accountLink.setAttribute('aria-label','Account');accountLink.innerHTML='<span class="account-icon" aria-hidden="true"></span>';tools.prepend(accountLink);}});
document.querySelectorAll('.footer').forEach((footer)=>{const emailInput=footer.querySelector('input[placeholder="Enter your email"]');const subscribeButton=emailInput?.parentElement?.querySelector('button');if(!emailInput||!subscribeButton||emailInput.form)return;const form=document.createElement('form');form.className='footer-newsletter-form';emailInput.replaceWith(form);form.append(emailInput,subscribeButton);emailInput.name='email';emailInput.type='email';emailInput.required=true;form.addEventListener('submit',async(event)=>{event.preventDefault();const email=emailInput.value.trim().toLowerCase();if(window.beadSupabase){const {error}=await window.beadSupabase.rpc('subscribe_to_newsletter',{subscriber_email:email});if(error){form.dataset.status=error.message;return;}}else{const subscribers=JSON.parse(localStorage.getItem('beadDifferentNotificationSubscribers')||'[]');if(!subscribers.includes(email))subscribers.push(email);localStorage.setItem('beadDifferentNotificationSubscribers',JSON.stringify(subscribers));}form.dataset.status='You are signed up for updates.';emailInput.value='';});});
const ensureHeaderSupabase=()=>{if(window.beadSupabaseReady)return window.beadSupabaseReady;return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='supabase-client.js?v=20260912-3';script.onload=()=>window.beadSupabaseReady?.then(resolve,reject);script.onerror=()=>reject(new Error('Supabase client failed to load.'));document.head.append(script);});};const hydrateCloudCategories=async()=>{const client=await ensureHeaderSupabase();const result=await client.from('categories').select('slug,name,cover_photo').eq('active',true).order('sort_order').order('name');if(result.error)throw result.error;const normalizedCategories=[['shop-all','Shop All'],...(result.data||[]).map((category)=>[category.slug,category.name]).filter((category,index,array)=>array.findIndex((entry)=>entry[0]===category[0])===index)];window.storeCategories=normalizedCategories;document.querySelectorAll('.store-nav').forEach((nav)=>{const links=categoryLayout?normalizedCategories.map(([slug,label])=>`<a href="category.html?category=${slug}" data-category-slug="${slug}"><span>${label}</span></a>`).join(''):normalizedCategories.map(([slug,label])=>`<a href="category.html?category=${slug}">${label}</a>`).join('');nav.replaceChildren();nav.insertAdjacentHTML('afterbegin',links);});document.querySelectorAll('.store-nav-select').forEach((select)=>{select.innerHTML='<option value="">Browse categories</option>'+normalizedCategories.map(([slug,label])=>`<option value="${slug}">${label}</option>`).join('');});const categoryGrid=document.querySelector('.category-grid');if(categoryGrid){categoryGrid.innerHTML=(result.data||[]).map((category)=>`<a href="category.html?category=${category.slug}" data-filter="${category.slug}"><img src="${category.cover_photo||'product-mix.jpg'}" alt="${category.name}"><b>${category.name}</b></a>`).join('');}window.dispatchEvent(new CustomEvent('bead-categories-ready',{detail:{categories:normalizedCategories}}));};const cloudCategoriesReady=hydrateCloudCategories().catch((error)=>{window.storeCategoryError=error;return[];});
window.siteSettingsReady=(async()=>{try{await cloudCategoriesReady;const client=window.beadSupabase;if(!client)return null;const {data,error}=await client.rpc('get_storefront_shipping_settings');if(error)return null;const value=data||{};const config=window.productStoreConfig||{};Object.assign(config,value);window.productStoreConfig=config;window.updateAnnouncementBar({freeShippingThreshold:value.freeShippingThreshold,smallBusiness:value.smallBusinessMessage,bigCreativity:value.bigCreativityMessage});window.siteShippingSettings={shippingPolicy:value.shippingPolicy||''};const policy=document.querySelector('[data-shipping-policy]');if(policy)policy.innerHTML=window.sanitizeRichText(window.siteShippingSettings.shippingPolicy||'Shipping options and delivery estimates are shown at checkout. Please contact us if your order arrives with a problem so we can help.');return value;}catch(error){return null;}})();
const canonicalShippingPolicyFallback='Shipping options and delivery estimates are shown at checkout. Please contact us if your order arrives with a problem so we can help.';
window.canonicalShippingPolicy=()=>{if(window.siteShippingSettings?.shippingPolicy)return window.siteShippingSettings.shippingPolicy;try{const settings=JSON.parse(localStorage.getItem('beadDifferentAdminData')||'{}').settings||{};if(settings.shippingPolicy)return settings.shippingPolicy;}catch(error){}return canonicalShippingPolicyFallback;};
window.renderCanonicalShippingPolicies=()=>{document.querySelectorAll('[data-shipping-policy]').forEach((element)=>{element.innerHTML=window.sanitizeRichText(window.canonicalShippingPolicy());});};
window.siteSettingsReady.then(()=>window.renderCanonicalShippingPolicies());
window.siteSettingsReady.then((value)=>window.applyStoreTheme(value?.theme,value?.heroUrl,value?.categoryPhotos,value?.logoUrl,value?.storyUrl,value?.pageBackgroundImageUrl,value?.footerLogoUrl));
window.addEventListener('bead-categories-ready',()=>{const selected=new URLSearchParams(location.search).get('category')||'';document.querySelectorAll('.store-nav a[data-category-slug]').forEach((link)=>{if(link.dataset.categorySlug===selected)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');});});
