const routes={"shop-all":"shop-all.html","new-arrivals":"new-arrivals.html","focal-beads":"focal-beads.html","acrylic-beads":"acrylic-beads.html","silicone-beads":"silicone-beads.html",rhinestones:"rhinestones.html",flatbacks:"flatbacks.html","pen-supplies":"pen-supplies.html","mixes-kits":"mixes-kits.html",clearance:"clearance.html",categories:"categories.html","our-story":"our-story.html",contact:"contact.html",search:"search.html",wishlist:"wishlist.html",bag:"shopping-bag.html"};
const headerRoot=document.querySelector('#site-header');
if(headerRoot){headerRoot.innerHTML=`<div class="announcement"><span class="announcement-item">FREE SHIPPING ON ORDERS $50+</span><span class="announcement-divider">✦</span><span class="announcement-item">SMALL BUSINESS</span><span class="announcement-heart">♥</span><span class="announcement-item">BIG CREATIVITY</span></div><header class="header"><a class="brand" href="index.html"><img src="logo-final.jpg" alt="Bead Different Co."></a><nav class="primary" aria-label="Main navigation"><a href="shop-all.html">Shop All</a><a href="categories.html">Categories</a><a href="our-story.html">Our Story</a><a href="contact.html">Contact</a></nav><div class="header-tools"><form class="search" action="search.html" method="get"><span class="search-icon" aria-hidden="true">⌕</span><input name="q" type="search" placeholder="Search beads, charms..." aria-label="Search beads, charms"></form><a class="tool" href="wishlist.html" aria-label="Wishlist">♡</a><a class="tool bag" href="shopping-bag.html" aria-label="Shopping bag"><span class="bag-icon"></span><i>0</i></a></div></header><nav class="store-nav" aria-label="Store categories"><a href="shop-all.html">Shop All</a><a href="new-arrivals.html">New Arrivals</a><a href="focal-beads.html">Focal Beads</a><a href="acrylic-beads.html">Acrylic Beads</a><a href="silicone-beads.html">Silicone Beads</a><a href="rhinestones.html">Rhinestones</a><a href="flatbacks.html">Flatbacks</a><a href="pen-supplies.html">Pen Supplies</a><a href="mixes-kits.html">Mixes & Kits</a><a href="clearance.html">Clearance</a></nav>`;document.body.classList.add('shared-header-page');}
const headerLogo=document.querySelector('#site-header .brand img');
if(headerLogo){headerLogo.src='logo-user-transparent.png?v=1';}
const footerRoot=document.querySelector('#site-footer')||document.body.appendChild(document.createElement('div'));footerRoot.id='site-footer';
if(footerRoot){footerRoot.innerHTML=`<section class="trust"><img class="trust-strip-image" src="trust-strip.png" alt="Fast shipping, small business, quality supplies, and amazing community"></section><footer class="footer" id="contact"><div class="footer-brand">Bead Different Co.<small>BEADS · SUPPLIES · CREATIVE POSSIBILITIES</small></div><div><b>Quick Links</b><a href="shop-all.html">Shop All</a><a href="our-story.html">About Us</a><a href="faq.html">FAQ</a><a href="shipping-returns.html">Shipping & Returns</a><a href="contact.html">Contact Us</a></div><div><b>Let’s Stay Connected</b><div class="social-links"><a href="#" aria-label="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="11" fill="currentColor"></circle><path fill="#111" d="M13.6 7.1h2V4.3c-.35-.05-1.55-.15-2.95-.15-2.92 0-4.92 1.78-4.92 5.05v2.82H4.5v3.13h3.23v7.86h3.95v-7.86h3.1l.49-3.13h-3.59V9.53c0-.91.25-1.53 1.92-1.53Z"></path></svg></a><a href="#" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="2"></rect><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="2"></circle><circle cx="17.5" cy="6.5" r="1.2" fill="currentColor"></circle></svg></a><a href="#" aria-label="TikTok"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M14.2 3h3.1c.25 1.65 1.18 2.74 2.7 3.28v3.08c-1.12-.03-2.13-.32-3.03-.86v6.13c0 3.76-2.25 5.98-5.64 5.98-3.02 0-5.23-1.97-5.23-4.76 0-3.02 2.45-5.08 5.91-4.69v3.2c-1.19-.22-2.15.27-2.15 1.35 0 .83.64 1.4 1.55 1.4 1.03 0 1.69-.68 1.69-2.37V3Z"></path></svg></a><a href="#" aria-label="Pinterest"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="10.5" fill="none" stroke="currentColor" stroke-width="2"></circle><path fill="currentColor" d="M10.1 19.4c.7-1.02 1.08-2.05 1.4-3.2.3.18.78.31 1.31.31 2.62 0 4.5-2.39 4.5-5.56 0-2.4-2.03-4.59-5.1-4.59-3.83 0-5.77 2.75-5.77 5.04 0 1.39.53 2.63 1.67 3.1.19.08.36 0 .42-.21l.16-.65c.05-.21.03-.28-.12-.47-.33-.4-.54-.92-.54-1.65 0-2.12 1.59-4.02 4.13-4.02 2.25 0 3.49 1.37 3.49 3.2 0 2.41-1.07 4.45-2.66 4.45-.88 0-1.54-.73-1.33-1.63.25-1.08.74-2.25.74-3.03 0-.7-.38-1.28-1.17-1.28-.93 0-1.67.96-1.67 2.25 0 .82.28 1.37.28 1.37s-.96 4.08-1.13 4.8c-.16.66-.18 1.4-.11 1.99Z"></path></svg></a><a href="#" aria-label="YouTube"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="2" y="5" width="20" height="14" rx="4" fill="currentColor"></rect><path fill="#111" d="m10 9 6 3-6 3V9Z"></path></svg></a></div></div><div><b>Join Our Newsletter</b><span>Get the latest drops, restocks and exclusive offers.</span><label><input placeholder="Enter your email"><button>SUBSCRIBE</button></label></div></footer>`;}
const footerBrand=footerRoot.querySelector('.footer-brand');
if(footerBrand){footerBrand.innerHTML='<img class="footer-logo" src="footer-logo.png" alt="Bead Different Co.">';}
const footerLogo=document.querySelector('#site-footer .footer-logo');
if(footerLogo){footerLogo.src='logo-user-footer.png?v=1';}
document.addEventListener('click',(event)=>{const link=event.target.closest('a[data-filter]');if(!link)return;const route=routes[link.dataset.filter];if(route){event.preventDefault();window.location.href=route;}});
const canonicalCategories=[['shop-all','Shop All'],['beadable-products','Beadable Products'],['beadable-pen-blanks','Beadable Pen Blanks'],['mixes-bundles-kits','Mixes, Bundles & Kits'],['spacers-accessories','Spacers/Accessories'],['acrylic-flatbacks','Acrylic Flatbacks'],['rhinestone-beads','Rhinestone Beads'],['focal-beads','Focal Beads'],['silicone-solid-color','Silicone Solid Color'],['silicone-printed-style','Silicone Printed Style'],['10-12mm-acrylic-beads','10/12mm Acrylic Beads'],['16mm-acrylic-beads','16mm Acrylic Beads'],['20mm-acrylic-beads','20mm Acrylic Beads'],['cup-charms','Cup Charms'],['completed-pens-keychains','Completed Pens/Keychains'],['charms-dangles','Charms/Dangles'],['clearance-section','Clearance Section']];
document.querySelectorAll('.store-nav').forEach((nav)=>{nav.innerHTML=canonicalCategories.map(([slug,label])=>`<a href="category.html?category=${slug}">${label}</a>`).join('');});
document.querySelectorAll('.store-nav').forEach((nav)=>{if(nav.parentElement.classList.contains('store-nav-shell'))return;const shell=document.createElement('div');shell.className='store-nav-shell';const previous=document.createElement('button');previous.className='store-nav-arrow';previous.type='button';previous.setAttribute('aria-label','Previous categories');previous.textContent='‹';const next=document.createElement('button');next.className='store-nav-arrow';next.type='button';next.setAttribute('aria-label','Next categories');next.textContent='›';nav.parentNode.insertBefore(shell,nav);shell.append(previous,nav,next);previous.addEventListener('click',()=>nav.scrollBy({left:-nav.clientWidth*.8,behavior:'smooth'}));next.addEventListener('click',()=>nav.scrollBy({left:nav.clientWidth*.8,behavior:'smooth'}));});
const categoryLayout=document.body.dataset.categoryLayout==='true';
if(categoryLayout){document.body.classList.add('category-layout');document.querySelectorAll('.store-nav').forEach((nav)=>{nav.classList.add('category-sidebar');nav.innerHTML=canonicalCategories.map(([slug,label])=>`<a href="category.html?category=${slug}" data-category-slug="${slug}"><span>${label}</span><strong data-category-count="${slug}">0</strong></a>`).join('');const shell=nav.closest('.store-nav-shell');const previous=shell?.querySelector('.store-nav-arrow');const next=shell?.querySelector('.store-nav-arrow:last-child');if(previous&&next){previous.textContent='↑';next.textContent='↓';previous.setAttribute('aria-label','Scroll categories up');next.setAttribute('aria-label','Scroll categories down');previous.addEventListener('click',()=>nav.scrollBy({top:-nav.clientHeight*.8,behavior:'smooth'}));next.addEventListener('click',()=>nav.scrollBy({top:nav.clientHeight*.8,behavior:'smooth'}));}});document.querySelector('#site-footer')?.classList.add('category-footer');}
window.updateCategoryCounts=(items)=>{if(!categoryLayout)return;const counts=items.reduce((result,item)=>{result[item.category]=(result[item.category]||0)+1;return result;},{'shop-all':items.length});document.querySelectorAll('[data-category-count]').forEach((count)=>{count.textContent=counts[count.dataset.categoryCount]||0;});};
document.querySelectorAll('.store-nav').forEach((nav)=>{const first=nav.querySelector('a');if(!first)return;first.href='shop-all.html';const label=first.querySelector('span');if(label)label.textContent='Shop All';else first.textContent='Shop All';});
if(categoryLayout&&window.matchMedia('(max-width:700px)').matches){document.querySelectorAll('.store-nav-shell').forEach((shell)=>{const arrows=shell.querySelectorAll('.store-nav-arrow');if(arrows.length===2){arrows[0].textContent='‹';arrows[1].textContent='›';arrows[0].setAttribute('aria-label','Scroll categories left');arrows[1].setAttribute('aria-label','Scroll categories right');}});}
document.querySelectorAll('.footer').forEach((footer)=>{const links=footer.querySelector('.footer-links')||footer.querySelector('div:nth-child(2)');if(links&&!links.querySelector('[href="reviews.html"]')){const reviewLink=document.createElement('a');reviewLink.href='reviews.html';reviewLink.textContent='Leave a Review';links.append(reviewLink);}});
document.querySelectorAll('.header-tools').forEach((tools)=>{if(!tools.querySelector('[href="account.html"]')){const accountLink=document.createElement('a');accountLink.href='account.html';accountLink.className='tool account-link';accountLink.setAttribute('aria-label','Account');accountLink.textContent='♙';tools.prepend(accountLink);}});
