const productPageEscape=(value)=>String(value??'').replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));

function productOptionPrice(option,value){
  if(value&&typeof value==='object')return Number(value.price)||0;
  const match=String(value).match(/\(\s*([+-])\s*\$?(\d+(?:\.\d{1,2})?)\s*\)/);
  if(!match)return 0;
  const amount=Number(match[2]);
  return match[1]==='-'?-amount:amount;
}

function renderProductPage(item){
  const main=document.querySelector('main');
  const images=item.images.length?item.images:[item.image];
  const basePrice=Number(item.price)||0;
  const config=window.productStoreConfig||{};
  const shippingPolicy=window.canonicalShippingPolicy?.()||'Shipping options and delivery estimates are shown at checkout. Please contact us if your order arrives with a problem so we can help.';
  const optionMarkup=(item.options||[]).map((option,index)=>`<label class="product-option"><span>${productPageEscape(option.name)}</span><select data-option-index="${index}"><option value="">Select an option</option>${option.values.map((value)=>{const label=typeof value==='object'?value.label:value;return`<option value="${productPageEscape(label)}">${productPageEscape(label)}</option>`;}).join('')}</select></label>`).join('');
  main.innerHTML=`<section class="store-page product-detail-page"><a class="back-to-results" href="javascript:history.back()">← Back to results</a><div class="product-page-layout"><div class="product-page-left"><div class="product-page-gallery"><div class="product-page-media"><img class="product-page-main-image" src="${productPageEscape(images[0])}" alt="${productPageEscape(item.name)}"></div><div class="product-page-thumbnails">${images.map((image,index)=>`<button type="button" class="product-page-thumbnail${index===0?' active':''}" data-image="${productPageEscape(image)}" aria-label="View image ${index+1}"><img src="${productPageEscape(image)}" alt=""></button>`).join('')}</div></div><section class="product-page-reviews"><h2>Reviews</h2><p>Reviews for this item will appear here once reviews are enabled.</p></section></div><div class="product-page-purchase"><p class="kicker">${productPageEscape(item.category.replaceAll('-',' ').toUpperCase())}</p><h1>${productPageEscape(item.name)}</h1><div class="product-page-rating">♡ Favorite this item</div><strong class="product-page-price" data-base-price="${item.price}">$${item.price.toFixed(2)}</strong><p class="product-page-stock">${item.quantity>0?`${item.quantity} in stock`:'Availability confirmed at checkout'}</p><div class="product-page-shipping"><strong>Ships from ${productPageEscape(config.shippingFrom||'our studio')}</strong><label for="delivery-zip">Deliver to</label><div class="delivery-estimate"><input id="delivery-zip" inputmode="numeric" placeholder="ZIP code" maxlength="10"><span data-arrival>Enter your ZIP for an estimate</span></div></div>${optionMarkup?`<section class="product-options"><h2>Choose your options</h2>${optionMarkup}</section>`:''}<label class="product-quantity">Quantity<select data-quantity><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label><div class="product-actions product-page-actions"><button type="button" class="cart-toggle${isInBag(item.id)?' in-cart':''}">${isInBag(item.id)?'Remove from Cart':'Add to Cart'}</button><button type="button" class="wishlist-button${wishlistItems().includes(item.id)?' active':''}" aria-label="Favorite">♡</button></div><div class="purchase-note">Secure checkout will be connected to the store payment provider.</div><div class="product-page-sections product-page-sections-side"><section><h2>Item details</h2><dl><div><dt>SKU</dt><dd data-selected-sku>${productPageEscape(item.sku||'')}</dd></div>${item.materials?`<div><dt>Materials</dt><dd>${productPageEscape(item.materials)}</dd>`:''}<div><dt>Category</dt><dd>${productPageEscape(item.category.replaceAll('-',' '))}</dd></div></dl></section><section><h2>Product description</h2><p>${productPageEscape(item.description).replace(/\r?\n/g,'<br>')}</p></section><section><h2>Shipping & returns</h2><div data-shipping-policy>${window.sanitizeRichText(shippingPolicy)}</div></section></div></div></div></section>`;
  const detailSections=main.querySelector('.product-page-sections-side');
  const detailBlock=[...detailSections.querySelectorAll('section')].find((section)=>section.querySelector('h2')?.textContent.toLowerCase()==='product details');
  const descriptionBlock=[...detailSections.querySelectorAll('section')].find((section)=>section.querySelector('h2')?.textContent.toLowerCase()==='product description');
  if(detailBlock&&descriptionBlock)detailSections.insertBefore(descriptionBlock,detailBlock);
  const quantitySelect=main.querySelector('[data-quantity]');
  for(let quantity=6;quantity<=20;quantity+=1){const option=document.createElement('option');option.value=quantity;option.textContent=quantity;quantitySelect.append(option);}
  const cartButton=main.querySelector('.cart-toggle');
  let waitlistSelected=false;
  const price=main.querySelector('.product-page-price');
  let priceUnit=price?.querySelector('[data-price-unit]');
  if(price&&!priceUnit){priceUnit=document.createElement('span');priceUnit.dataset.priceUnit='';price.append(' ',priceUnit);}
  const selectedOptionEntries=()=>[...main.querySelectorAll('[data-option-index]')].map((select,index)=>{const option=item.options?.[index];const configured=(option?.values||[]).find((value)=>typeof value==='object'?value.label===select.value:value===select.value);return{option,configured,label:select.value};}).filter((entry)=>entry.label);
  const requiredOptionsReady=()=> (item.options||[]).every((option,index)=>option.required===false||Boolean(main.querySelector(`[data-option-index="${index}"]`)?.value));
  const selectedVariant=()=>{const entry=selectedOptionEntries().find(({option})=>String(option?.name||'').trim().toLowerCase()==='sku')||((item.options||[]).length===1?selectedOptionEntries()[0]:null);if(!entry)return null;return typeof entry.configured==='object'?entry.configured:{label:entry.label,price:basePrice+productOptionPrice(entry.option,entry.configured),unitType:'Each'};};
  const promoActive=()=>Number(item.promoDiscountPercent)>0&&(!(item.promoStartsAt||item.promo_starts_at)||Date.parse(item.promoStartsAt||item.promo_starts_at)<=Date.now())&&(!(item.promoEndsAt||item.promo_ends_at)||Date.parse(item.promoEndsAt||item.promo_ends_at)>=Date.now());
  const updatePrice=()=>{const selected=selectedVariant();let total=selected&&typeof selected==='object'&&selected.price!==undefined?Number(selected.price):basePrice;if(selected&&promoActive()&&(item.promoSkus||[]).map((sku)=>String(sku).toLowerCase()).includes(String(selected.sku||'').toLowerCase()))total*=1-(Math.min(100,Math.max(0,Number(item.promoDiscountPercent)||0))/100);if(price){price.firstChild.textContent=`$${total.toFixed(2)}`;priceUnit.textContent=`/ ${selected?.unitType||item.unitType||'Each'}`;}};
  const updateVariantDisplay=()=>{updatePrice();const selected=selectedVariant();const sku=main.querySelector('[data-selected-sku]');if(sku)sku.textContent=selected?.sku||item.sku||'—';const image=main.querySelector('.product-page-main-image');if(image)image.src=selected?.imageUrl||images[0];main.querySelectorAll('.product-page-thumbnail').forEach((thumbnail,index)=>thumbnail.classList.toggle('active',selected?.imageUrl?thumbnail.dataset.image===selected.imageUrl:index===0));syncStockButton();};
  main.querySelectorAll('[data-option-index]').forEach((select)=>select.addEventListener('change',updateVariantDisplay));
  main.querySelectorAll('[data-image]').forEach((button)=>button.addEventListener('click',()=>{main.querySelector('.product-page-main-image').src=button.dataset.image;main.querySelectorAll('.product-page-thumbnail').forEach((thumbnail)=>thumbnail.classList.toggle('active',thumbnail===button));}));
  main.querySelector('#delivery-zip')?.addEventListener('input',(event)=>{const arrival=config.estimateArrival?.(event.target.value);main.querySelector('[data-arrival]').textContent=arrival?`Estimated arrival ${arrival}`:'Enter your ZIP for an estimate';});
  const waitlistEnabled=item.waitlist!==false&&!config.waitlistDisabled?.[item.id];
  const stockMessage=document.createElement('p');stockMessage.className='stock-threshold-message';cartButton.before(stockMessage);
  const syncStockButton=()=>{if(!requiredOptionsReady()){waitlistSelected=false;stockMessage.textContent='Choose an option before adding this item to your cart.';main.querySelector('.product-page-stock').textContent='Select an option to see availability';cartButton.textContent='Choose an option';cartButton.classList.remove('restock-button','in-cart');cartButton.disabled=true;return;}const requested=Number(quantitySelect.value);const selected=selectedVariant();const available=selected&&selected.quantity!==null&&selected.quantity!==undefined?Number(selected.quantity):Number(item.quantity)||0;waitlistSelected=requested>available;if(!waitlistSelected){stockMessage.textContent='';main.querySelector('.product-page-stock').textContent=available>0?`${available} in stock`:'Availability confirmed at checkout';cartButton.textContent=isInBag(item.id,selectedOptionsForCart())?'Remove from Cart':'Add to Cart';cartButton.classList.remove('restock-button');cartButton.disabled=false;return;}if(!waitlistEnabled){stockMessage.textContent=available?`Only ${available} in stock. Choose ${available} or fewer.`:'Currently out of stock. Waitlist is unavailable for this item.';cartButton.textContent=available?'Choose an available quantity':'Unavailable';cartButton.classList.add('restock-button');cartButton.disabled=true;return;}stockMessage.textContent=`Only ${available} of ${requested} are available. Buy the available amount and waitlist the rest, or waitlist the full requested quantity.`;cartButton.textContent=available?'Choose how to handle the unavailable amount':'Waitlist the full requested quantity';cartButton.classList.add('restock-button');cartButton.disabled=false;};
  quantitySelect.addEventListener('change',()=>{if(window.storeControls?.salesFrozen){cartButton.disabled=true;cartButton.textContent='Sales paused for inventory audit';}else syncStockButton();});
  const selectedOptionsForCart=()=>selectedOptionEntries().map(({configured,label})=>({label,sku:configured?.sku||'',inventorySku:configured?.inventorySku||'',inventoryUnits:Number(configured?.inventoryUnits)||1,imageUrl:configured?.imageUrl||'',price:Number(configured?.price)||basePrice,unitType:configured?.unitType||'Each',weight:configured?.weight??null,weightUnit:configured?.weightUnit||'oz'}));
  if(window.storeControls?.salesFrozen){cartButton.disabled=true;cartButton.textContent='Sales paused for inventory audit';}else syncStockButton();
  cartButton.addEventListener('click',async()=>{if(window.storeControls?.salesFrozen)return;if(!requiredOptionsReady())return;const selectedOptions=selectedOptionsForCart();if(waitlistSelected){const requested=Number(quantitySelect.value);const selected=selectedVariant();const availableStock=selected&&selected.quantity!==null&&selected.quantity!==undefined?Number(selected.quantity):Number(item.quantity)||0;const requestMode=await window.restockWaitlist.chooseMode(requested,availableStock);if(!requestMode)return;const account=await window.restockWaitlist.requestAccount();if(!account)return;const available=requestMode==='partial'?Math.min(availableStock,requested):0;const waitlistedQuantity=requestMode==='full'?requested:Math.max(0,requested-availableStock);const options=[...main.querySelectorAll('[data-option-index]')].map((select)=>select.value).filter(Boolean);const inventorySku=selected?.inventorySku||selected?.sku||selectedOptions.find((option)=>option.inventorySku)?.inventorySku||item.sku||'';options.push(`Requested quantity: ${requested}`);options.push(`Available at request: ${availableStock}`);options.push(`Waitlisted quantity: ${waitlistedQuantity}`);const joined=await window.restockWaitlist.join({productId:item.id,productName:item.name,accountEmail:account.email,requestedQuantity:waitlistedQuantity,requestedTotalQuantity:requested,availableQuantityAtRequest:availableStock,requestMode:requestMode==='full'?'full':'partial',inventorySku,selectedOptions,options});if(requestMode==='partial'){for(let count=0;count<available;count+=1)addToBag(item.id,selectedOptions);}cartButton.textContent=joined?(available?`Added ${available} + Waitlisted`:'Waitlist Joined'):'Already on waitlist';cartButton.disabled=true;return;}if(isInBag(item.id,selectedOptions)){removeFromBag(item.id,selectedOptions);cartButton.textContent='Add to Cart';cartButton.classList.remove('in-cart');}else{for(let count=0;count<Number(quantitySelect.value);count+=1)addToBag(item.id,selectedOptions);cartButton.textContent='Remove from Cart';cartButton.classList.add('in-cart');}});
  main.querySelector('.wishlist-button').addEventListener('click',(event)=>{event.currentTarget.classList.toggle('active',toggleWishlist(item.id));});
}

catalogReady.then(async()=>{await window.shippingSettingsReady;const productId=new URLSearchParams(location.search).get('id');const item=findProduct(productId);const main=document.querySelector('main');if(!item||!isProductVisible(item)){main.innerHTML='<section class="store-page product-unavailable"><h1>Item unavailable</h1><p>This item is not currently available for purchase.</p><a class="cta" href="shop-all.html">Continue shopping</a></section>';return;}if(!item.externalId){const response=await fetch('etsy-listings.csv');const rows=parseCsv(await response.text());item.quantity=Number.parseInt(rows[catalog.indexOf(item)]?.QUANTITY,10)||0;}trackProductEvent(item.id,'view');renderProductPage(item);});
const finalProductPageRenderer=renderProductPage;
renderProductPage=(item)=>{finalProductPageRenderer(item);const media=document.querySelector('.product-page-media');(item.media||[]).filter((entry)=>entry.type==='video').forEach((entry)=>{const video=document.createElement('video');video.src=entry.url;video.controls=true;video.preload='metadata';video.className='product-page-video';video.setAttribute('aria-label',`${item.name} video`);media?.append(video);});document.querySelectorAll('.product-page-badges,.product-page-badges-above').forEach((row)=>row.remove());const allBadges=[...(item.badges||[]),...(window.storefrontStatusBadges?.(item)||[])];const aboveBadges=allBadges.filter((badge)=>!['On Sale','Clearance','Low Stock','Out of Stock'].includes(badge));const inventoryBadges=allBadges.filter((badge)=>['On Sale','Clearance','Low Stock','Out of Stock'].includes(badge));const badgeSpan=(badge)=>`<span class="product-badge product-badge-${String(badge).toLowerCase().replace(/[^a-z0-9]+/g,'-')}">${productPageEscape(badge)}</span>`;if(!media||!allBadges.length)return;if(aboveBadges.length){const aboveRow=document.createElement('div');aboveRow.className='product-badges-above';aboveRow.innerHTML=aboveBadges.map(badgeSpan).join('');media.parentElement?.insertBefore(aboveRow,media);}if(inventoryBadges.length){const inventoryRow=document.createElement('div');inventoryRow.className='product-badges product-page-badges';inventoryRow.innerHTML=inventoryBadges.map(badgeSpan).join('');media.append(inventoryRow);}};
