const promoStoreKey='beadDifferentPromos';
const promoSessionKey='beadStorePromosV1';
const promoSessionTtl=60000;
let promoRecords=[];
const readPromos=()=>promoRecords.length?promoRecords:(()=>{try{return JSON.parse(localStorage.getItem(promoStoreKey)||'[]');}catch(error){return [];}})();
const savePromos=(promos)=>{promoRecords=promos;localStorage.setItem(promoStoreKey,JSON.stringify(promos));};
const promoIsActive=(promo)=>promo?.active!==false&&(!promo.starts_at||Date.parse(promo.starts_at)<=Date.now())&&(!promo.ends_at||Date.parse(promo.ends_at)>=Date.now());
const promoDiscountLabel=(promo)=>promo.mode==='banner'?'':promo.discount_type==='percent'||promo.type==='percent'?`${Number(promo.value||0)}% off`:`$${Number(promo.value||0).toFixed(2)} off`;
const promoEndLabel=(value)=>{const date=new Date(value||'');return Number.isNaN(date.getTime())?'':date.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});};
function promoDiscount(promo,subtotal){if(!promo||!promoIsActive(promo))return 0;const snapshot=window.storeCartPricingSnapshot;const snapshotSubtotal=Number(snapshot?.subtotal);const amount=Number.isFinite(snapshotSubtotal)&&Math.abs(snapshotSubtotal-(Number(subtotal)||0))<0.005?Math.max(0,Number(snapshot.promoEligibleSubtotal??subtotal)||0):Math.max(0,Number(subtotal)||0);const value=Math.max(0,Number(promo.value)||0);return Math.min(amount,promo.discount_type==='percent'||promo.type==='percent'?amount*(value/100):value);}
function findPromo(code){const normalized=String(code||'').trim().toUpperCase();const configured=readPromos().find((promo)=>promoIsActive(promo)&&(promo.code||'').toUpperCase()===normalized);if(configured)return configured;try{const account=JSON.parse(localStorage.getItem('beadDifferentAccount')||'null');const rewards=JSON.parse(localStorage.getItem('beadDifferentRewardCodes')||'[]');const reward=rewards.find((entry)=>entry.accountId===account?.id&&!entry.redeemedAt&&(entry.code||'').toUpperCase()===normalized);if(reward)return{code:reward.code,mode:'manual',discount_type:'percent',value:reward.discountPercent,active:true};}catch(error){}return null;}
async function findPromoAsync(code){const local=findPromo(code);if(local)return local;if(!window.beadSupabase)return null;const result=await window.beadSupabase.rpc('lookup_test_promo',{promo_code:String(code||'').trim()});if(result.error)throw result.error;return result.data||null;}
function autoPromo(subtotal=0){return readPromos().filter((promo)=>promo.mode==='auto'&&promoIsActive(promo)).sort((a,b)=>promoDiscount(b,subtotal)-promoDiscount(a,subtotal))[0]||null;}
function homepagePromo(){return readPromos().filter((promo)=>['auto','banner'].includes(promo.mode)&&promo.show_homepage_banner===true&&promoIsActive(promo)).sort((a,b)=>Number(b.mode==='banner')-Number(a.mode==='banner')||promoDiscount(b,0)-promoDiscount(a,0))[0]||null;}
function renderHomepagePromoBanner(){document.querySelector('.homepage-promo-banner')?.remove();document.querySelector('.homepage-promo-details-dialog')?.remove();const promo=homepagePromo();const host=document.querySelector('#site-header');if(!promo||!host||!document.querySelector('.hero'))return;const banner=document.createElement('aside');banner.className='homepage-promo-banner';banner.setAttribute('aria-label','Current promotion');const mark=document.createElement('span');mark.className='homepage-promo-banner-mark';mark.setAttribute('aria-hidden','true');mark.textContent='✦';const content=document.createElement('div');content.className='homepage-promo-banner-content';const title=document.createElement('strong');title.textContent=promo.title||promo.code||'Special offer';const displayText=promo.banner_text||(['auto'].includes(promo.mode)?[promoDiscountLabel(promo),promoEndLabel(promo.ends_at)?`Ends ${promoEndLabel(promo.ends_at)}`:''].filter(Boolean).join(' · '):'See offer details for more.');const details=document.createElement('span');details.className='homepage-promo-banner-details';details.textContent=displayText;content.append(title,details);if(String(promo.details||'').trim()){const detailsButton=document.createElement('button');detailsButton.type='button';detailsButton.className='homepage-promo-banner-details-button';detailsButton.textContent='Offer Details';const dialog=document.createElement('dialog');dialog.className='homepage-promo-details-dialog';dialog.innerHTML='<button type="button" class="homepage-promo-details-close" aria-label="Close offer details">×</button><div class="homepage-promo-details-content"><p class="kicker">OFFER DETAILS</p><h2></h2><div class="homepage-promo-details-copy"></div></div>';dialog.querySelector('h2').textContent=title.textContent;dialog.querySelector('.homepage-promo-details-copy').textContent=promo.details;dialog.querySelector('.homepage-promo-details-close').addEventListener('click',()=>dialog.close());detailsButton.addEventListener('click',()=>dialog.showModal());content.append(detailsButton);document.body.append(dialog);}banner.append(mark,content,mark.cloneNode(true));host.insertAdjacentElement('beforebegin',banner);}
const safePromoLink=(value)=>{const raw=String(value||'').trim();if(!raw)return'';try{const parsed=new URL(raw,window.location.href);return parsed.origin===window.location.origin&&['http:','https:'].includes(parsed.protocol)?parsed.href:'';}catch(error){return'';}};
const addHomepagePromoDestination=()=>{const dialog=document.querySelector('.homepage-promo-details-dialog');const href=safePromoLink(homepagePromo()?.banner_link);if(!dialog||!href||dialog.querySelector('.homepage-promo-details-link'))return;const link=document.createElement('a');link.className='homepage-promo-details-link';link.href=href;link.textContent='Shop this offer';dialog.querySelector('.homepage-promo-details-content')?.append(link);};
window.storePromos={read:readPromos,save:savePromos,find:findPromo,findAsync:findPromoAsync,auto:autoPromo,homepage:homepagePromo,discount:promoDiscount,discountLabel:promoDiscountLabel};
window.storePromosReady=(async()=>{let cached=null;try{const record=JSON.parse(sessionStorage.getItem(promoSessionKey)||'null');if(record?.at&&Date.now()-Number(record.at)<promoSessionTtl&&Array.isArray(record.data))cached=record.data;}catch(error){}if(cached!==null){promoRecords=cached;return promoRecords.length?promoRecords:readPromos();}const client=await (window.beadSupabaseReady||Promise.resolve(window.beadSupabase));if(client){const {data,error}=await client.from('promo_codes').select('id,title,code,discount_type,value,mode,active,starts_at,ends_at,show_homepage_banner,banner_text,details,banner_link').eq('active',true).in('mode',['auto','banner']).order('starts_at',{ascending:false}).range(0,99);if(!error&&data){promoRecords=data;try{sessionStorage.setItem(promoSessionKey,JSON.stringify({at:Date.now(),data}));}catch(error){}}}return promoRecords.length?promoRecords:readPromos();})();
window.storePromosReady.then(()=>{renderHomepagePromoBanner();addHomepagePromoDestination();});
