const promoStoreKey='beadDifferentPromos';
let promoRecords=[];
const readPromos=()=>promoRecords.length?promoRecords:(()=>{try{return JSON.parse(localStorage.getItem(promoStoreKey)||'[]');}catch(error){return [];}})();
const savePromos=(promos)=>{promoRecords=promos;localStorage.setItem(promoStoreKey,JSON.stringify(promos));};
const promoIsActive=(promo)=>promo?.active!==false&&(!promo.starts_at||Date.parse(promo.starts_at)<=Date.now())&&(!promo.ends_at||Date.parse(promo.ends_at)>=Date.now());
const promoDiscountLabel=(promo)=>promo.discount_type==='percent'||promo.type==='percent'?`${Number(promo.value||0)}% off`:`$${Number(promo.value||0).toFixed(2)} off`;
const promoEndLabel=(value)=>{const date=new Date(value||'');return Number.isNaN(date.getTime())?'':date.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});};
function promoDiscount(promo,subtotal){if(!promo||!promoIsActive(promo))return 0;const snapshot=window.storeCartPricingSnapshot;const snapshotSubtotal=Number(snapshot?.subtotal);const amount=Number.isFinite(snapshotSubtotal)&&Math.abs(snapshotSubtotal-(Number(subtotal)||0))<0.005?Math.max(0,Number(snapshot.promoEligibleSubtotal??subtotal)||0):Math.max(0,Number(subtotal)||0);const value=Math.max(0,Number(promo.value)||0);return Math.min(amount,promo.discount_type==='percent'||promo.type==='percent'?amount*(value/100):value);}
function findPromo(code){const normalized=String(code||'').trim().toUpperCase();const configured=readPromos().find((promo)=>promoIsActive(promo)&&(promo.code||'').toUpperCase()===normalized);if(configured)return configured;try{const account=JSON.parse(localStorage.getItem('beadDifferentAccount')||'null');const rewards=JSON.parse(localStorage.getItem('beadDifferentRewardCodes')||'[]');const reward=rewards.find((entry)=>entry.accountId===account?.id&&!entry.redeemedAt&&(entry.code||'').toUpperCase()===normalized);if(reward)return{code:reward.code,mode:'manual',discount_type:'percent',value:reward.discountPercent,active:true};}catch(error){}return null;}
async function findPromoAsync(code){const local=findPromo(code);if(local)return local;if(!window.beadSupabase)return null;const result=await window.beadSupabase.rpc('lookup_test_promo',{promo_code:String(code||'').trim()});if(result.error)throw result.error;return result.data||null;}
function autoPromo(subtotal=0){return readPromos().filter((promo)=>promo.mode==='auto'&&promoIsActive(promo)).sort((a,b)=>promoDiscount(b,subtotal)-promoDiscount(a,subtotal))[0]||null;}
function homepagePromo(){return readPromos().filter((promo)=>promo.mode==='auto'&&promo.show_homepage_banner===true&&promoIsActive(promo)).sort((a,b)=>promoDiscount(b,0)-promoDiscount(a,0))[0]||null;}
function renderHomepagePromoBanner(){const existing=document.querySelector('.homepage-promo-banner');existing?.remove();const promo=homepagePromo();const host=document.querySelector('#site-header');if(!promo||!host||!document.querySelector('.hero'))return;const banner=document.createElement('aside');banner.className='homepage-promo-banner';banner.setAttribute('aria-label','Current promotion');const title=document.createElement('strong');title.textContent=promo.title||promo.code||'Special offer';const details=document.createElement('span');details.textContent=promoEndLabel(promo.ends_at)?`${promoDiscountLabel(promo)} · Ends ${promoEndLabel(promo.ends_at)}`:promoDiscountLabel(promo);banner.append(title,details);host.insertAdjacentElement('afterend',banner);}
window.storePromos={read:readPromos,save:savePromos,find:findPromo,findAsync:findPromoAsync,auto:autoPromo,homepage:homepagePromo,discount:promoDiscount,discountLabel:promoDiscountLabel};
window.storePromosReady=window.beadSupabase?window.beadSupabase.from('promo_codes').select('id,title,code,discount_type,value,mode,active,starts_at,ends_at,show_homepage_banner').eq('mode','auto').then(({data,error})=>{if(!error&&data)promoRecords=data;return promoRecords;}):Promise.resolve(readPromos());
window.storePromosReady.then(()=>renderHomepagePromoBanner());
