const reviewStoreKey='beadDifferentReviews';
const readReviews=()=>{try{return JSON.parse(localStorage.getItem(reviewStoreKey)||'[]');}catch(error){return [];}};
const saveReviews=(reviews)=>localStorage.setItem(reviewStoreKey,JSON.stringify(reviews));
const reviewEscape=(value)=>String(value??'').replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
function purchasedItemIds(){try{return new Set(JSON.parse(localStorage.getItem('beadDifferentPurchasedItems')||'[]'));}catch(error){return new Set();}}
async function optimizeReviewImage(file){if(!file.type.startsWith('image/'))throw new Error('Review attachments must be images.');if(file.size>15*1024*1024)throw new Error('Review photos must be 15 MB or smaller.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);return new Promise((resolve)=>canvas.toBlob((blob)=>resolve(new File([blob],`${file.name.replace(/\.[^.]+$/,'')}.jpg`,{type:'image/jpeg'})),'image/jpeg',.82));}
async function uploadReviewPhotos(files,userId){const photos=[];for(const [index,file] of Array.from(files||[]).slice(0,5).entries()){const optimized=await optimizeReviewImage(file);const path=`reviews/${userId}/${Date.now()}-${index}-${optimized.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-')}`;const result=await window.beadSupabase.storage.from('product-media').upload(path,optimized,{upsert:false,contentType:'image/jpeg',cacheControl:'31536000'});if(result.error)throw result.error;photos.push(window.beadSupabase.storage.from('product-media').getPublicUrl(path).data.publicUrl);}return photos;}
async function submitReview(review){if(window.beadSupabase){const {data:{user}}=await window.beadSupabase.auth.getUser();if(!user)throw new Error('Please log in before leaving a review.');let productId=null;if(review.productId){const {data:product}=await window.beadSupabase.from('products').select('id').eq('external_id',review.productId).maybeSingle();if(!product)throw new Error('Purchased item not found.');productId=product.id;}const photos=await uploadReviewPhotos(review.photos,user.id);const {error}=await window.beadSupabase.from('reviews').insert({user_id:user.id,product_id:productId,review_type:review.type,rating:review.rating,body:review.body,photos,verified_purchase:review.type==='item'});if(error)throw error;return true;}const account=window.restockWaitlist?.currentAccount();if(!account)throw new Error('Please log in before leaving a review.');const reviews=readReviews();reviews.push({...review,id:`review-${Date.now()}`,email:account.email,status:'pending',createdAt:new Date().toISOString()});saveReviews(reviews);return true;}
window.reviewTools={read:readReviews,save:saveReviews,purchasedItemIds,submit:submitReview,escape:reviewEscape};
