(async()=>{
  const form=document.querySelector('#review-form'),formPanel=document.querySelector('[data-review-form-panel]'),openForm=document.querySelector('[data-open-review-form]'),closeForm=document.querySelector('[data-close-review-form]'),summary=document.querySelector('[data-review-summary]'),list=document.querySelector('[data-review-list]');
  form?.querySelector('button.cta')?.replaceChildren(document.createTextNode('Submit review'));
  const escape=window.reviewTools?.escape||((value)=>String(value??'').replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character])));
  const decodeText=(value)=>{const node=document.createElement('textarea');node.innerHTML=String(value??'');return node.value;};
  const formatDate=(value)=>{const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleDateString();};
  const formatMemberSince=(value)=>formatDate(value);
  const reviewPhotoMarkup=(review)=>{const photos=Array.isArray(review.photos)?review.photos:[];const links=photos.slice(0,5).map((photo,index)=>{const safe=escape(photo);return `<a href='${safe}' target='_blank' rel='noopener noreferrer'><img src='${safe}' alt='Review photo ${index+1}' loading='lazy'></a>`;}).join('');return links?`<div class='website-review-photos'>${links}</div>`:'';};
  const stars=(rating)=>{const value=Math.max(0,Math.min(5,Number(rating)||0));return '★'.repeat(Math.round(value))+'☆'.repeat(5-Math.round(value));};
  openForm?.addEventListener('click',async()=>{let signedIn=Boolean(window.customerAccounts?.current?.());if(window.beadSupabase){const {data}=await window.beadSupabase.auth.getUser();signedIn=Boolean(data?.user);}if(!signedIn){const status=document.querySelector('#review-status');status.className='review-status-error';status.textContent='Please sign in to leave a review.';return;}formPanel.hidden=false;formPanel.scrollIntoView({behavior:'smooth',block:'start'});});
  closeForm?.addEventListener('click',()=>{formPanel.hidden=true;});
  let reviews=[],selectedRating=0,page=1;
  const renderSummary=()=>{const counts=[1,2,3,4,5].map((rating)=>reviews.filter((review)=>Number(review.rating)===rating).length),total=reviews.length,average=total?reviews.reduce((sum,review)=>sum+Number(review.rating||0),0)/total:0;summary.innerHTML=total?`<div class="review-summary-rating"><strong>${average.toFixed(1)}</strong><span>${stars(average)}</span><small>${total} review${total===1?'':'s'}</small></div><div class="review-summary-breakdown">${[5,4,3,2,1].map((rating)=>`<div class="review-rating-row"><span>${rating} stars</span><button type="button" class="review-summary-bar" data-review-rating="${rating}" aria-label="Show ${rating}-star reviews"><i style="width:${total?(counts[rating-1]/total)*100:0}%"></i></button><button type="button" class="review-rating-count ${selectedRating===rating?'active':''}" data-review-rating="${rating}">${counts[rating-1]}</button></div>`).join('')}<button type="button" class="review-rating-all ${selectedRating===0?'active':''}" data-review-rating="0">Show all reviews</button></div>`:'<div class="admin-empty">No approved website reviews yet.</div>';summary.querySelectorAll('[data-review-rating]').forEach((button)=>button.addEventListener('click',()=>{selectedRating=Number(button.dataset.reviewRating)||0;page=1;renderSummary();renderList();}));};
  const renderList=()=>{const filtered=selectedRating?reviews.filter((review)=>Number(review.rating)===selectedRating):reviews,totalPages=Math.max(1,Math.ceil(filtered.length/5)),currentPage=Math.min(page,totalPages),start=(currentPage-1)*5;page=currentPage;list.innerHTML=filtered.slice(start,start+5).map((review)=>`<article class="website-review"><div class="website-review-stars" aria-label="${Number(review.rating)||0} out of 5 stars">${stars(review.rating)}</div><p>${escape(decodeText(review.body||''))}</p><span>${escape(decodeText(review.reviewer_name||review.author_name||'Customer'))}${review.reviewer_member_since?` · Member since ${formatMemberSince(review.reviewer_member_since)}`:''} · ${formatDate(review.created_at)}</span>${reviewPhotoMarkup(review)}${review.admin_response?`<div class="website-review-response"><strong>Bead Different Co.</strong><p>${escape(decodeText(review.admin_response))}</p></div>`:''}</article>`).join('')||'<div class="admin-empty">No reviews match that rating.</div>';if(filtered.length)list.insertAdjacentHTML('beforeend',`<div class="review-pagination"><button type="button" data-review-page="prev" ${currentPage===1?'disabled':''}>Previous</button><span>Page ${currentPage} of ${totalPages} · ${filtered.length} reviews</span><button type="button" data-review-page="next" ${currentPage===totalPages?'disabled':''}>Next</button></div>`);list.querySelector('[data-review-page="prev"]')?.addEventListener('click',()=>{page-=1;renderList();});list.querySelector('[data-review-page="next"]')?.addEventListener('click',()=>{page+=1;renderList();});};
  try{if(window.beadSupabaseReady)await window.beadSupabaseReady;if(!window.beadSupabase)throw new Error('Supabase is not connected.');for(let offset=0;;offset+=1000){const result=await window.beadSupabase.from('reviews').select('rating,body,photos,reviewer_name,author_name,reviewer_member_since,created_at,admin_response').eq('review_type','website').eq('status','approved').order('created_at',{ascending:false}).range(offset,offset+999);if(result.error)throw result.error;reviews.push(...(result.data||[]));if((result.data||[]).length<1000)break;}renderSummary();renderList();}catch(error){summary.innerHTML='<div class="admin-empty">Reviews are temporarily unavailable.</div>';list.replaceChildren();}
  form.addEventListener('submit',async(event)=>{event.preventDefault();const status=document.querySelector('#review-status'),submitButton=form.querySelector('button[type="submit"]')||form.querySelector('button');if(!submitButton)return;submitButton.disabled=true;status.className='review-status-pending';status.textContent='Submitting your review…';try{const fields=Object.fromEntries(new FormData(form));await window.reviewTools.submit({type:fields.type,productId:fields.productId||null,rating:Number(fields.rating),body:fields.body,photos:form.querySelector('[name="photos"]').files});form.reset();formPanel.hidden=false;status.className='review-status-success';status.textContent='Your review was submitted.';status.scrollIntoView({behavior:'smooth',block:'center'});}catch(error){status.className='review-status-error';status.textContent=error.message||'Your review could not be submitted.';}finally{submitButton.disabled=false;}});
})();
