const names={'shop-all':'All','new-arrivals':'New Arrivals','beadable-products':'Beadable Products','beadable-pen-blanks':'Beadable Pen Blanks','mixes-bundles-kits':'Mixes, Bundles & Kits','spacers-accessories':'Spacers/Accessories','acrylic-flatbacks':'Acrylic Flatbacks','rhinestone-beads':'Rhinestone Beads','focal-beads':'Focal Beads','silicone':'Silicone','acrylic':'Acrylic','10-12mm-acrylic-beads':'10/12mm Acrylic Beads','16mm-acrylic-beads':'16mm Acrylic Beads','20mm-acrylic-beads':'20mm Acrylic Beads','cup-charms':'Cup Charms','completed-pens-keychains':'Completed Pens/Keychains','charms-dangles':'Charms/Dangles','clearance-section':'Clearance Section'};
const grid=document.querySelector('#product-grid'),view=document.querySelector('#filter-view'),filtered=document.querySelector('#filtered-items'),title=document.querySelector('#filter-title'),count=document.querySelector('#filter-count');
const categoryGrid=document.querySelector('.category-grid');
document.querySelector('.category-prev')?.addEventListener('click',()=>categoryGrid?.scrollBy({left:-categoryGrid.clientWidth*.8,behavior:'smooth'}));
document.querySelector('.category-next')?.addEventListener('click',()=>categoryGrid?.scrollBy({left:categoryGrid.clientWidth*.8,behavior:'smooth'}));
const categoryLinks=window.storeCategories;
document.querySelectorAll('.store-nav').forEach((nav)=>{nav.innerHTML=categoryLinks.map(([slug,label])=>`<a href="category.html?category=${slug}">${label}</a>`).join('');});
document.querySelectorAll('.category-grid').forEach((grid)=>{const siliconeLinks=[...grid.querySelectorAll('[data-filter="silicone-solid-color"],[data-filter="silicone-printed-style"]')];if(siliconeLinks.length){const silicone=siliconeLinks[0].cloneNode(true);silicone.href='#filter=silicone';silicone.dataset.filter='silicone';silicone.querySelector('b').textContent='Silicone';siliconeLinks.forEach((link)=>link.remove());grid.insertBefore(silicone,grid.children[8]||null);}const acrylicLinks=[...grid.querySelectorAll('[data-filter="10-12mm-acrylic-beads"],[data-filter="16mm-acrylic-beads"],[data-filter="20mm-acrylic-beads"]')];if(acrylicLinks.length){const acrylic=acrylicLinks[0].cloneNode(true);acrylic.href='#filter=acrylic';acrylic.dataset.filter='acrylic';acrylic.querySelector('b').textContent='Acrylic';acrylicLinks.forEach((link)=>link.remove());grid.insertBefore(acrylic,grid.children[9]||null);}});
document.querySelectorAll('[data-filter="cup-charms"] img').forEach((image)=>{image.src='cup-charms.jpg';image.alt='Cup charms';});
function applyFilter(filter){if(filter==='new-arrivals'){window.location.href='new-arrivals.html';return;}if(filter==='silicone'||filter==='acrylic'){window.location.href=`category.html?category=${filter}`;return;}if(!view||!filtered){window.location.href=`category.html?category=${encodeURIComponent(filter)}`;return;}const list=visibleCatalog().filter((item)=>filter==='shop-all'||item.category===filter);title.textContent=names[filter]||'All';count.textContent=`${list.length} ${list.length===1?'item':'items'}`;renderProductCards(list,filtered);view.classList.add('active');view.scrollIntoView({block:'start'});}
catalogReady.then(()=>{document.querySelectorAll('[data-filter]').forEach((link)=>link.addEventListener('click',()=>applyFilter(link.dataset.filter)));renderProductCards(visibleCatalog().slice(0,6),grid);const filter=new URLSearchParams(location.hash.slice(1)).get('filter');if(filter)applyFilter(filter);});
window.addEventListener('hashchange',()=>{const filter=new URLSearchParams(location.hash.slice(1)).get('filter');if(filter)applyFilter(filter);});
