function shortProductTitle(title){const parts=title.split(',').map((part)=>part.trim()).filter(Boolean);const first=parts[0]||'Bead';const generic=/^(beads?|3d beads|printed beads|silicone beads|focal beads)$/i;if(generic.test(first)&&parts[1]&&!/^(diy|beads? for|beads? in bulk|bead supplies?|loose beads?|small beads?)/i.test(parts[1]))return`${first.replace(/s$/i,'')} ${parts[1]}`.replace(/\s+/g,' ').trim();return first.replace(/\s+/g,' ').trim();}
let catalog=[];
const categoryOptions=['beadable-products','beadable-pen-blanks','mixes-bundles-kits','spacers-accessories','acrylic-flatbacks','rhinestone-beads','focal-beads','silicone-solid-color','silicone-printed-style','10-12mm-acrylic-beads','16mm-acrylic-beads','20mm-acrylic-beads','cup-charms','completed-pens-keychains','charms-dangles','clearance-section'];
const storeKeys={bag:'beadDifferentBag',wishlist:'beadDifferentWishlist'};
const readStore=(key)=>JSON.parse(localStorage.getItem(key)||'[]');
const writeStore=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let index=0;index<text.length;index+=1){const char=text[index],next=text[index+1];if(char==='"'&&quoted&&next==='"'){cell+='"';index+=1;}else if(char==='"'){quoted=!quoted;}else if(char===','&&!quoted){row.push(cell);cell='';}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')index+=1;row.push(cell);if(row.some((value)=>value!==''))rows.push(row);row=[];cell='';}else cell+=char;}if(cell||row.length){row.push(cell);rows.push(row);}const headers=rows.shift().map((header)=>header.replace(/^\uFEFF/,''));return rows.map((values)=>Object.fromEntries(headers.map((header,index)=>[header,values[index]||''])));}
function categoryFor(row){const titleTags=`${row.TITLE} ${row.TAGS}`.toLowerCase();if(titleTags.includes('clearance'))return'clearance-section';if(/completed.*(pen|keychain)|finished.*(pen|keychain)/.test(titleTags))return'completed-pens-keychains';if(/cup accessories, cup charm,/.test(titleTags))return'cup-charms';if((titleTags.includes('charm')||titleTags.includes('dangle'))&&!titleTags.includes('cup charm'))return'charms-dangles';if(titleTags.includes('focal'))return'focal-beads';if(titleTags.includes('flatback'))return'acrylic-flatbacks';if(titleTags.includes('rhinestone'))return'rhinestone-beads';if((titleTags.includes('spacer')||titleTags.includes('accessor'))&&!titleTags.includes('cup charm')&&!titleTags.includes('cup accessor'))return'spacers-accessories';if(titleTags.includes('mix')||titleTags.includes('bundle')||titleTags.includes('kit'))return'mixes-bundles-kits';if(/beadable.*pen.*blank|beaded.*pen.*blank|pen.*blank/.test(titleTags))return'beadable-pen-blanks';if(/10\s*(\/|or)\s*12\s*mm|10mm|12mm/.test(titleTags)&&titleTags.includes('acrylic'))return'10-12mm-acrylic-beads';if(/16\s*mm/.test(titleTags)&&titleTags.includes('acrylic'))return'16mm-acrylic-beads';if(/20\s*mm/.test(titleTags)&&titleTags.includes('acrylic'))return'20mm-acrylic-beads';if(titleTags.includes('silicone'))return(/print|paw|letter|face|pattern|design|swirl/.test(titleTags)?'silicone-printed-style':'silicone-solid-color');return'uncategorized';}
async function loadCatalog(){const response=await fetch('etsy-listings.csv');const rows=parseCsv(await response.text());catalog=rows.map((row,index)=>({id:(row.SKU||`${row.TITLE}-${index}`).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),name:shortProductTitle(row.TITLE),seoTitle:row.TITLE,searchText:[row.TITLE,row.TAGS,row.DESCRIPTION,row.MATERIALS].filter(Boolean).join(' '),addedAt:row['DATE ADDED']||row.DATE_ADDED||row.CREATED_AT||row.LISTING_DATE||'2026-09-09T00:00:00-04:00',category:categoryFor(row),image:row.IMAGE1||'product-mix.jpg',images:[row.IMAGE1,row.IMAGE2,row.IMAGE3,row.IMAGE4,row.IMAGE5].filter(Boolean),price:Number.parseFloat(row.PRICE)||0,description:row.DESCRIPTION,sku:row.SKU,tags:row.TAGS,materials:row.MATERIALS}));return catalog;}
const catalogReady=loadCatalog();
window.catalogReady=catalogReady;
const findProduct=(id)=>catalog.find((item)=>item.id===id);
const searchCatalog=(query)=>{const needle=String(query||'').trim().toLowerCase();if(!needle)return catalog;return catalog.filter((item)=>item.searchText.toLowerCase().includes(needle));};
window.searchCatalog=searchCatalog;
const bagItems=()=>readStore(storeKeys.bag);
const wishlistItems=()=>readStore(storeKeys.wishlist);
const isInBag=(id)=>bagItems().some((item)=>item.id===id);
function updateBagCount(){const count=bagItems().reduce((total,item)=>total+item.quantity,0);document.querySelectorAll('#bag-count,.bag i').forEach((element)=>{element.textContent=count;});}
function addToBag(id){const item=findProduct(id);if(item&&!isProductVisible(item))return false;const items=bagItems();const existing=items.find((entry)=>entry.id===id);if(existing)existing.quantity+=1;else items.push({id,quantity:1});writeStore(storeKeys.bag,items);updateBagCount();return true;}
function removeFromBag(id){writeStore(storeKeys.bag,bagItems().filter((item)=>item.id!==id));updateBagCount();}
function toggleWishlist(id){const items=wishlistItems();const index=items.indexOf(id);if(index===-1)items.push(id);else items.splice(index,1);writeStore(storeKeys.wishlist,items);return index===-1;}
function openProductDetails(id){const item=findProduct(id);if(!item)return;let modal=document.querySelector('#product-modal');if(!modal){modal=document.createElement('dialog');modal.id='product-modal';document.body.append(modal);}modal.innerHTML=`<button class="modal-close" type="button" aria-label="Close">×</button><div class="product-detail product-modal-detail"><div class="product-gallery">${item.images.map((image,index)=>`<img loading="lazy" src="${image}" alt="${item.name} image ${index+1}">`).join('')}</div><div><p class="kicker">${item.category.replaceAll('-',' ').toUpperCase()}</p><h2>${item.name}</h2><strong>$${item.price.toFixed(2)}</strong><p>${item.description.replace(/\n/g,'<br>')}</p><a class="cta" href="product.html?id=${encodeURIComponent(item.id)}">View All Details</a></div></div>`;modal.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',(event)=>{if(event.target===modal)modal.close();},{once:true});modal.showModal();}
function renderProductCards(list,target,options={}){if(!target)return;const wished=wishlistItems();target.replaceChildren(...list.map((item)=>{const inBag=isInBag(item.id);const card=document.createElement('article');card.className='product-card';card.dataset.seoTitle=item.seoTitle;card.dataset.searchText=item.searchText;card.innerHTML=`<img loading="lazy" class="product-card-image" src="${item.image}" alt="${item.name}"><h3>${item.name}</h3><strong>$${item.price.toFixed(2)}</strong><div class="product-actions"><button type="button" class="cart-toggle${inBag?' in-cart':''}" data-cart-toggle="${item.id}">${inBag?'Remove from Cart':'Add to Cart'}</button><button type="button" class="wishlist-button${wished.includes(item.id)?' active':''}" data-wishlist="${item.id}" aria-label="${wished.includes(item.id)?'Remove from':'Add to'} wishlist">♡</button>${options.cart?`<button type="button" class="remove-cart" data-remove="${item.id}">Remove</button>`:''}</div>`;card.addEventListener('click',(event)=>{if(!event.target.closest('button'))openProductDetails(item.id);});return card;}));target.querySelectorAll('[data-cart-toggle]').forEach((button)=>button.addEventListener('click',()=>{if(isInBag(button.dataset.cartToggle)){removeFromBag(button.dataset.cartToggle);button.textContent='Add to Cart';button.classList.remove('in-cart');}else{addToBag(button.dataset.cartToggle);button.textContent='Remove from Cart';button.classList.add('in-cart');}}));target.querySelectorAll('[data-remove]').forEach((button)=>button.addEventListener('click',()=>{removeFromBag(button.dataset.remove);button.closest('.product-card').remove();const empty=document.querySelector('#store-empty');if(empty&&!target.children.length)empty.hidden=false;}));target.querySelectorAll('[data-wishlist]').forEach((button)=>button.addEventListener('click',()=>{const active=toggleWishlist(button.dataset.wishlist);button.classList.toggle('active',active);}));}
document.addEventListener('DOMContentLoaded',updateBagCount);
function renderPaginatedProducts(list,target,controls,options={}){if(!target)return;const pageSize=24;let currentPage=1;const draw=()=>{const pageCount=Math.max(1,Math.ceil(list.length/pageSize));currentPage=Math.min(currentPage,pageCount);renderProductCards(list.slice((currentPage-1)*pageSize,currentPage*pageSize),target,options);if(!controls)return;controls.replaceChildren();if(pageCount<2)return;for(let page=1;page<=pageCount;page+=1){const button=document.createElement('button');button.type='button';button.textContent=page;button.className=page===currentPage?'active':'';button.addEventListener('click',()=>{currentPage=page;draw();target.scrollIntoView({block:'start'});});controls.append(button);}};draw();}
const beadableProductPatterns=[/^pen ink refills/,/^rod extender/,/^beadable earrings/,/^beadable pen packaging bags/,/^beadable garden tool set/,/^wine stopper/,/^beadable ornament/,/^beadable bar keychain/,/^beadable keychain,/,/^makeup brushes/,/^carabiner,/,/^beadable box cutter/,/^beadable stylus/,/^beaded pencil blank/,/^beadable bookmarks/,/^beadable crochet hook/,/^beadable cup straw keychain/,/^pack of keychain blanks/,/^beadable bar,/,/^beadable cup straw attachment/,/^cup charm wire/,/^dog paw keychain bars/,/^sticker heart beadable cup charm blank/,/^badge reel,/,/^beadable mirrors/,/^beadable bars,/,/^pack of pencils/,/^beadable keychain blanks/,/^box cutters/,/^diy snowflake keychains/,/^beadable blanks, teacher id holder/,/^beadable dog poop bag holder/,/^plastic comb/,/^full set of beadable keychains/,/^bottle opener/,/^bullet earrings/,/^beadable badge reel pens/,/^badge reels,/];
function categoryFor(row){const titleTags=`${row.TITLE} ${row.TAGS}`.toLowerCase();if(beadableProductPatterns.some((pattern)=>pattern.test(titleTags)))return'beadable-products';if(titleTags.includes('clearance'))return'clearance-section';if(/completed.*(pen|keychain)|finished.*(pen|keychain)/.test(titleTags))return'completed-pens-keychains';if(/cup accessories, cup charm,/.test(titleTags))return'cup-charms';if((titleTags.includes('charm')||titleTags.includes('dangle'))&&!titleTags.includes('cup charm'))return'charms-dangles';if(titleTags.includes('focal'))return'focal-beads';if(titleTags.includes('flatback'))return'acrylic-flatbacks';if(titleTags.includes('rhinestone'))return'rhinestone-beads';if((titleTags.includes('spacer')||titleTags.includes('accessor'))&&!titleTags.includes('cup charm')&&!titleTags.includes('cup accessor'))return'spacers-accessories';if(titleTags.includes('mix')||titleTags.includes('bundle')||titleTags.includes('kit'))return'mixes-bundles-kits';if(/beadable.*pen.*blank|beaded.*pen.*blank|pen.*blank/.test(titleTags))return'beadable-pen-blanks';if(/10\s*(\/|or)\s*12\s*mm|10mm|12mm/.test(titleTags)&&titleTags.includes('acrylic'))return'10-12mm-acrylic-beads';if(/16\s*mm/.test(titleTags)&&titleTags.includes('acrylic'))return'16mm-acrylic-beads';if(/20\s*mm/.test(titleTags)&&titleTags.includes('acrylic'))return'20mm-acrylic-beads';if(titleTags.includes('silicone'))return(/print|paw|letter|face|pattern|design|swirl/.test(titleTags)?'silicone-printed-style':'silicone-solid-color');return'uncategorized';}
const originalCategoryFor=categoryFor;
const penBlankOverrides=[/^crayon beaded pen/,/^snowman beaded pen/,/^st\. patrick.?s day beadable pen set/];
categoryFor=(row)=>penBlankOverrides.some((pattern)=>pattern.test(`${row.TITLE} ${row.TAGS}`.toLowerCase()))?'beadable-pen-blanks':originalCategoryFor(row);
const escapeProductText=(value)=>String(value||'').replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
openProductDetails=(id)=>{const item=findProduct(id);if(!item)return;let modal=document.querySelector('#product-modal');if(!modal){modal=document.createElement('dialog');modal.id='product-modal';document.body.append(modal);}const images=item.images.length?item.images:[item.image];modal.innerHTML=`<button class="modal-close" type="button" aria-label="Close">×</button><div class="product-modal-detail"><div class="product-modal-gallery"><img class="product-main-image" src="${escapeProductText(images[0])}" alt="${escapeProductText(item.name)}"><div class="product-thumbnails" role="list">${images.map((image,index)=>`<button type="button" class="product-thumbnail${index===0?' active':''}" data-image="${escapeProductText(image)}" aria-label="View image ${index+1}"><img src="${escapeProductText(image)}" alt=""></button>`).join('')}</div></div><div class="product-modal-copy"><p class="kicker">${escapeProductText(item.category.replaceAll('-',' ').toUpperCase())}</p><h2>${escapeProductText(item.name)}</h2><strong>$${item.price.toFixed(2)}</strong><section><h3>Product Description</h3><p>${escapeProductText(item.description).replace(/\r?\n/g,'<br>')}</p></section><section><h3>Product Details</h3><dl>${item.sku?`<div><dt>SKU</dt><dd>${escapeProductText(item.sku)}</dd></div>`:''}${item.materials?`<div><dt>Materials</dt><dd>${escapeProductText(item.materials)}</dd></div>`:''}<div><dt>Search terms</dt><dd class="visually-muted">${escapeProductText(item.tags||'')}</dd></div></dl></section><a class="cta" href="product.html?id=${encodeURIComponent(item.id)}">View All Details</a></div></div>`;modal.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.querySelectorAll('[data-image]').forEach((button)=>button.addEventListener('click',()=>{modal.querySelector('.product-main-image').src=button.dataset.image;modal.querySelectorAll('.product-thumbnail').forEach((thumbnail)=>thumbnail.classList.toggle('active',thumbnail===button));}));modal.addEventListener('click',(event)=>{if(event.target===modal)modal.close();},{once:true});modal.showModal();};
const openProductDetailsBase=openProductDetails;
openProductDetails=(id)=>{openProductDetailsBase(id);const item=findProduct(id);const copy=document.querySelector('#product-modal .product-modal-copy');if(!item||!copy)return;const purchase=document.createElement('div');purchase.className='product-quick-actions';purchase.innerHTML=`<span class="product-stock">${item.quantity>0?`${item.quantity} in stock`:'Availability confirmed at checkout'}</span><button type="button" class="cart-toggle${isInBag(item.id)?' in-cart':''}">${isInBag(item.id)?'Remove from Cart':'Add to Cart'}</button><button type="button" class="wishlist-button${wishlistItems().includes(item.id)?' active':''}" aria-label="Favorite">♡</button>`;const description=copy.querySelector('section');copy.querySelector('strong').after(purchase);purchase.querySelector('.cart-toggle').addEventListener('click',(event)=>{if(isInBag(item.id)){removeFromBag(item.id);event.currentTarget.textContent='Add to Cart';event.currentTarget.classList.remove('in-cart');}else{addToBag(item.id);event.currentTarget.textContent='Remove from Cart';event.currentTarget.classList.add('in-cart');}});purchase.querySelector('.wishlist-button').addEventListener('click',(event)=>{event.currentTarget.classList.toggle('active',toggleWishlist(item.id));});const shipping=document.createElement('section');shipping.innerHTML='<h3>Shipping & Returns</h3><p>Shipping options and delivery estimates are shown at checkout. Please contact us if your order arrives with a problem so we can help.</p>';copy.insertBefore(shipping,copy.querySelector('.cta'));};
catalogReady.then(async()=>{const response=await fetch('etsy-listings.csv');const rows=parseCsv(await response.text());catalog.forEach((item,index)=>{item.quantity=Number.parseInt(rows[index]?.QUANTITY,10)||0;});});
renderProductCards=(list,target,options={})=>{if(!target)return;const wished=wishlistItems();target.replaceChildren(...list.map((item)=>{const inBag=isInBag(item.id);const card=document.createElement('article');card.className='product-card';card.dataset.seoTitle=item.seoTitle;card.dataset.searchText=item.searchText;card.innerHTML=`<a class="product-card-link" href="product.html?id=${encodeURIComponent(item.id)}"><img loading="lazy" class="product-card-image" src="${escapeProductText(item.image)}" alt="${escapeProductText(item.name)}"><h3>${escapeProductText(item.name)}</h3></a><strong>$${item.price.toFixed(2)}</strong><div class="product-actions"><button type="button" class="cart-toggle${inBag?' in-cart':''}" data-cart-toggle="${item.id}">${inBag?'Remove from Cart':'Add to Cart'}</button><button type="button" class="wishlist-button${wished.includes(item.id)?' active':''}" data-wishlist="${item.id}" aria-label="${wished.includes(item.id)?'Remove from':'Add to'} wishlist">♡</button>${options.cart?`<button type="button" class="remove-cart" data-remove="${item.id}">Remove</button>`:''}</div>`;return card;}));target.querySelectorAll('[data-cart-toggle]').forEach((button)=>button.addEventListener('click',()=>{if(isInBag(button.dataset.cartToggle)){removeFromBag(button.dataset.cartToggle);button.textContent='Add to Cart';button.classList.remove('in-cart');}else{addToBag(button.dataset.cartToggle);button.textContent='Remove from Cart';button.classList.add('in-cart');}}));target.querySelectorAll('[data-remove]').forEach((button)=>button.addEventListener('click',()=>{removeFromBag(button.dataset.remove);button.closest('.product-card').remove();}));target.querySelectorAll('[data-wishlist]').forEach((button)=>button.addEventListener('click',()=>{button.classList.toggle('active',toggleWishlist(button.dataset.wishlist));}));};
catalogReady.then(()=>window.updateCategoryCounts?.(catalog));
catalogReady.then(async()=>{const response=await fetch('etsy-listings.csv');const rows=parseCsv(await response.text());catalog.forEach((item,index)=>{const row=rows[index]||{};item.options=[1,2,3].map((number)=>({name:row[`VARIATION ${number} NAME`]||'',values:String(row[`VARIATION ${number} VALUES`]||'').split(/\s*[,|]\s*/).map((value)=>value.trim()).filter(Boolean)})).filter((option)=>option.name&&option.values.length);const configured=window.productStoreConfig?.options?.[item.id];if(configured)item.options=configured;});});
function hiddenProductIds(){const stored=localStorage.getItem('beadDifferentHiddenProducts');if(stored===null)return new Set(catalog.map((item)=>item.id));try{return new Set(JSON.parse(stored));}catch(error){return new Set(catalog.map((item)=>item.id));}}
function isProductVisible(item){return !hiddenProductIds().has(item.id);}
function visibleCatalog(){return catalog.filter(isProductVisible);}
window.isProductVisible=isProductVisible;
window.visibleCatalog=visibleCatalog;
searchCatalog=(query)=>{const needle=String(query||'').trim().toLowerCase();if(!needle)return visibleCatalog();return visibleCatalog().filter((item)=>item.searchText.toLowerCase().includes(needle));};
window.searchCatalog=searchCatalog;
